package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * CatFraccion generated by hbm2java
 */
@Entity
@Table(name = "cat_fraccion")
@NamedQueries({ @NamedQuery(name = "CatFraccion.findAll", query = "SELECT c FROM CatFraccion c") })
public class CatFraccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_fraccion")
	private Long idFraccion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_clase", nullable = false)
	private CatGeneral catClase;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioByUsuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioByUsuarioModificacion;
	
	@Column(name = "clave", nullable = false, length = 45)
	private String clave;
	
	@Column(name = "descripcion", nullable = false, length = 45)
	private String descripcion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;
//	private Set prestadoraServicioRegistroPatronals = new HashSet(0);

	public CatFraccion() {
	}

	public CatFraccion(CatGeneral catClase, Usuario usuarioByUsuarioAlta, String clave, String descripcion,
			Date fechaAlta, Long indEstatus) {
		this.catClase = catClase;
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
		this.clave = clave;
		this.descripcion = descripcion;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public CatFraccion(CatGeneral catClase, Usuario usuarioByUsuarioAlta, Usuario usuarioByUsuarioModificacion,
			String clave, String descripcion, Date fechaAlta, Date fechaModificacion, Long indEstatus) {
		this.catClase = catClase;
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
		this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
		this.clave = clave;
		this.descripcion = descripcion;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdFraccion() {
		return this.idFraccion;
	}

	public void setIdFraccion(Long idFraccion) {
		this.idFraccion = idFraccion;
	}


	public CatGeneral getCatClase() {
		return catClase;
	}

	public void setCatClase(CatGeneral catClase) {
		this.catClase = catClase;
	}

	public Usuario getUsuarioByUsuarioAlta() {
		return this.usuarioByUsuarioAlta;
	}

	public void setUsuarioByUsuarioAlta(Usuario usuarioByUsuarioAlta) {
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
	}

	
	public Usuario getUsuarioByUsuarioModificacion() {
		return this.usuarioByUsuarioModificacion;
	}

	public void setUsuarioByUsuarioModificacion(Usuario usuarioByUsuarioModificacion) {
		this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
	}

	
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	
	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catFraccion")
//	public Set getPrestadoraServicioRegistroPatronals() {
//		return this.prestadoraServicioRegistroPatronals;
//	}
//
//	public void setPrestadoraServicioRegistroPatronals(Set prestadoraServicioRegistroPatronals) {
//		this.prestadoraServicioRegistroPatronals = prestadoraServicioRegistroPatronals;
//	}

}
