package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicioCuentaBancaria generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio_cuenta_bancaria")
@NamedQueries({ @NamedQuery(name = "PrestadoraServicioCuentaBancaria.findAll", query = "SELECT c FROM PrestadoraServicioCuentaBancaria c") })
public class PrestadoraServicioCuentaBancaria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2796292979287706421L;


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_prestadora_servicio_cuenta_bancaria")
	private Long idPrestadoraServicioCuentaBancaria;
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_banco", nullable = false)
	private CatGeneral catBanco;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestadora_servicio", nullable = false)
	private PrestadoraServicio prestadoraServicio;
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;
	
	@Column(name = "numero_cuenta", length = 45)
	private String numeroCuenta;
	
	@Column(name = "clabe_interbancaria", length = 45)
	private String clabeInterbancaria;
	
	@Column(name = "es_principal", nullable = false)
	private int esPrincipal;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_cuenta", nullable = false)
	private CatGeneral catTipoCuenta;
	
	@Column(name = "numero_referencia")
	private String numeroReferencia;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public PrestadoraServicioCuentaBancaria() {
	}

	public PrestadoraServicioCuentaBancaria(CatGeneral catBanco, PrestadoraServicio prestadoraServicio,
			Usuario usuarioAlta, String numeroCuenta, String clabeInterbancaria, Date fechaAlta, Long indEstatus) {
		this.catBanco = catBanco;
		this.prestadoraServicio = prestadoraServicio;
		this.usuarioAlta = usuarioAlta;
		this.numeroCuenta = numeroCuenta;
		this.clabeInterbancaria = clabeInterbancaria;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public PrestadoraServicioCuentaBancaria(CatGeneral catBanco, PrestadoraServicio prestadoraServicio,
			Usuario usuarioAlta, String numeroCuenta, String clabeInterbancaria, Date fechaAlta, Date fechaModificacion,
			Long indEstatus) {
		this.catBanco = catBanco;
		this.prestadoraServicio = prestadoraServicio;
		this.usuarioAlta = usuarioAlta;
		this.numeroCuenta = numeroCuenta;
		this.clabeInterbancaria = clabeInterbancaria;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdPrestadoraServicioCuentaBancaria() {
		return idPrestadoraServicioCuentaBancaria;
	}

	public void setIdPrestadoraServicioCuentaBancaria(Long idPrestadoraServicioCuentaBancaria) {
		this.idPrestadoraServicioCuentaBancaria = idPrestadoraServicioCuentaBancaria;
	}

	public CatGeneral getCatBanco() {
		return catBanco;
	}

	public void setCatBanco(CatGeneral catBanco) {
		this.catBanco = catBanco;
	}

	public PrestadoraServicio getPrestadoraServicio() {
		return prestadoraServicio;
	}

	public void setPrestadoraServicio(PrestadoraServicio prestadoraServicio) {
		this.prestadoraServicio = prestadoraServicio;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public String getNumeroCuenta() {
		return numeroCuenta;
	}

	public void setNumeroCuenta(String numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	public String getClabeInterbancaria() {
		return clabeInterbancaria;
	}

	public void setClabeInterbancaria(String clabeInterbancaria) {
		this.clabeInterbancaria = clabeInterbancaria;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public int getEsPrincipal() {
		return esPrincipal;
	}

	public void setEsPrincipal(int esPrincipal) {
		this.esPrincipal = esPrincipal;
	}

	public CatGeneral getCatTipoCuenta() {
		return catTipoCuenta;
	}

	public void setCatTipoCuenta(CatGeneral catTipoCuenta) {
		this.catTipoCuenta = catTipoCuenta;
	}

	public String getNumeroReferencia() {
		return numeroReferencia;
	}

	public void setNumeroReferencia(String numeroReferencia) {
		this.numeroReferencia = numeroReferencia;
	}

}
