package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicioApoderadoLegalPoderNotarial generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio_apoderado_legal_poder_notarial")
@NamedQueries({ @NamedQuery(name = "PrestadoraServicioApoderadoLegalPoderNotarial.findAll", query = "SELECT c FROM PrestadoraServicioApoderadoLegalPoderNotarial c") })
public class PrestadoraServicioApoderadoLegalPoderNotarial implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_prestadora_servicio_apoderado_legal_poder_notarial")
	private Long idPrestadoraServicioApoderadoLegalPoderNotarial;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_poder_notarial", nullable = false)
	private CatGeneral catPoderNotarial;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestadora_servicio_apoderado_legal", nullable = false)
	private PrestadoraServicioApoderadoLegal prestadoraServicioApoderadoLegal;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public PrestadoraServicioApoderadoLegalPoderNotarial() {
	}

	public PrestadoraServicioApoderadoLegalPoderNotarial(CatGeneral catPoderNotarial,
			PrestadoraServicioApoderadoLegal prestadoraServicioApoderadoLegal, Usuario usuarioAlta, Date fechaAlta,
			Long indEstatus) {
		this.catPoderNotarial = catPoderNotarial;
		this.prestadoraServicioApoderadoLegal = prestadoraServicioApoderadoLegal;
		this.usuarioAlta = usuarioAlta;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public PrestadoraServicioApoderadoLegalPoderNotarial(CatGeneral catPoderNotarial,
			PrestadoraServicioApoderadoLegal prestadoraServicioApoderadoLegal, Usuario usuarioAlta, Date fechaAlta,
			Date fechaModificacion, Long indEstatus) {
		this.catPoderNotarial = catPoderNotarial;
		this.prestadoraServicioApoderadoLegal = prestadoraServicioApoderadoLegal;
		this.usuarioAlta = usuarioAlta;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}


	public Long getIdPrestadoraServicioApoderadoLegalPoderNotarial() {
		return this.idPrestadoraServicioApoderadoLegalPoderNotarial;
	}

	public void setIdPrestadoraServicioApoderadoLegalPoderNotarial(
			Long idPrestadoraServicioApoderadoLegalPoderNotarial) {
		this.idPrestadoraServicioApoderadoLegalPoderNotarial = idPrestadoraServicioApoderadoLegalPoderNotarial;
	}


	public PrestadoraServicioApoderadoLegal getPrestadoraServicioApoderadoLegal() {
		return this.prestadoraServicioApoderadoLegal;
	}

	public void setPrestadoraServicioApoderadoLegal(PrestadoraServicioApoderadoLegal prestadoraServicioApoderadoLegal) {
		this.prestadoraServicioApoderadoLegal = prestadoraServicioApoderadoLegal;
	}


	public CatGeneral getCatPoderNotarial() {
		return catPoderNotarial;
	}

	public void setCatPoderNotarial(CatGeneral catPoderNotarial) {
		this.catPoderNotarial = catPoderNotarial;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}


	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}


	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}


	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

}
