package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.seguridad.Persona;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicioAccionista generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio_accionista")
@NamedQueries({
		@NamedQuery(name = "PrestadoraServicioAccionista.findAll", query = "SELECT c FROM PrestadoraServicioAccionista c") })
public class PrestadoraServicioAccionista implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_prestadora_servicio_accionista")
	private Long idPrestadoraServicioAccionista;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	private Persona persona;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestadora_servicio", nullable = false)
	private PrestadoraServicio prestadoraServicio;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Column(name = "porcentaje_accion", nullable = false)
	private BigDecimal porcentajeAccion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public PrestadoraServicioAccionista() {
	}

	public PrestadoraServicioAccionista(Long idPrestadoraServicioAccionista) {
		this.idPrestadoraServicioAccionista = idPrestadoraServicioAccionista;
	}

	public Long getIdPrestadoraServicioAccionista() {
		return idPrestadoraServicioAccionista;
	}

	public void setIdPrestadoraServicioAccionista(Long idPrestadoraServicioAccionista) {
		this.idPrestadoraServicioAccionista = idPrestadoraServicioAccionista;
	}

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public PrestadoraServicio getPrestadoraServicio() {
		return prestadoraServicio;
	}

	public void setPrestadoraServicio(PrestadoraServicio prestadoraServicio) {
		this.prestadoraServicio = prestadoraServicio;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public BigDecimal getPorcentajeAccion() {
		return porcentajeAccion;
	}

	public void setPorcentajeAccion(BigDecimal porcentajeAccion) {
		this.porcentajeAccion = porcentajeAccion;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

}
