package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final


import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatEstatus;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicioEstatus generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio_estatus")
@NamedQueries({ @NamedQuery(name = "PrestadoraServicioEstatus.findAll", query = "SELECT c FROM PrestadoraServicioEstatus c") })
public class PrestadoraServicioEstatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_prestadora_servicio_estatus")
	private Long idPrestadoraServicioEstatus;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestadora_servicio", nullable = false)
	private PrestadoraServicio prestadoraServicio;
	
	@JoinColumn(name="id_cat_estatus")
	@ManyToOne(targetEntity = CatEstatus.class, cascade=CascadeType.ALL)
    private CatEstatus catEstatus;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public PrestadoraServicioEstatus() {
	}
	
	public PrestadoraServicioEstatus(Long idPrestadoraServicioEstatus) {
		this.idPrestadoraServicioEstatus = idPrestadoraServicioEstatus;
	}

	public Long getIdPrestadoraServicioEstatus() {
		return idPrestadoraServicioEstatus;
	}

	public void setIdPrestadoraServicioEstatus(Long idPrestadoraServicioEstatus) {
		this.idPrestadoraServicioEstatus = idPrestadoraServicioEstatus;
	}

	public PrestadoraServicio getPrestadoraServicio() {
		return prestadoraServicio;
	}

	public void setPrestadoraServicio(PrestadoraServicio prestadoraServicio) {
		this.prestadoraServicio = prestadoraServicio;
	}

	public CatEstatus getCatEstatus() {
		return catEstatus;
	}

	public void setCatEstatus(CatEstatus catEstatus) {
		this.catEstatus = catEstatus;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}


	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}
	
	


}
