package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.crm.Domicilio;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicioAccionistaDomicilio generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio_accionista_domicilio")
@NamedQueries({ @NamedQuery(name = "PrestadoraServicioAccionistaDomicilio.findAll", query = "SELECT c FROM PrestadoraServicioAccionistaDomicilio c") })
public class PrestadoraServicioAccionistaDomicilio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_prestadora_servicio_accionista_domicilio")
	private Long idPrestadoraServicioAccionistaDomicilio;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestadora_servicio_accionista", nullable = false)
	private PrestadoraServicioAccionista prestadoraServicioAccionista;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_domicilio", nullable = false)
	private Domicilio domicilio;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public PrestadoraServicioAccionistaDomicilio() {
	}
	
	public PrestadoraServicioAccionistaDomicilio(Long idPrestadoraServicioAccionistaDomicilio) {
		this.idPrestadoraServicioAccionistaDomicilio = idPrestadoraServicioAccionistaDomicilio;
	}

	public Long getIdPrestadoraServicioAccionistaDomicilio() {
		return idPrestadoraServicioAccionistaDomicilio;
	}

	public void setIdPrestadoraServicioAccionistaDomicilio(Long idPrestadoraServicioAccionistaDomicilio) {
		this.idPrestadoraServicioAccionistaDomicilio = idPrestadoraServicioAccionistaDomicilio;
	}

	public Domicilio getDomicilio() {
		return domicilio;
	}

	public void setDomicilio(Domicilio domicilio) {
		this.domicilio = domicilio;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public PrestadoraServicioAccionista getPrestadoraServicioAccionista() {
		return prestadoraServicioAccionista;
	}

	public void setPrestadoraServicioAccionista(PrestadoraServicioAccionista prestadoraServicioAccionista) {
		this.prestadoraServicioAccionista = prestadoraServicioAccionista;
	}
	
}
