package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.crm.Domicilio;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicioDomicilio generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio_domicilio")
@NamedQueries({ @NamedQuery(name = "PrestadoraServicioDomicilio.findAll", query = "SELECT c FROM PrestadoraServicioDomicilio c") })
public class PrestadoraServicioDomicilio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_prestadora_servicio_domicilio")
	private Long idPrestadoraServicioDomicilio;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestadora_servicio", nullable = false)
	private PrestadoraServicio prestadoraServicio;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_domicilio", nullable = false)
	private Domicilio domicilio;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioByUsuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioByUsuarioModificacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public PrestadoraServicioDomicilio() {
	}

	public PrestadoraServicioDomicilio(Domicilio domicilio, Usuario usuarioByUsuarioAlta, Date fechaAlta,
			Long indEstatus) {
		this.domicilio = domicilio;
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public PrestadoraServicioDomicilio(Domicilio domicilio, Usuario usuarioByUsuarioAlta,
			Usuario usuarioByUsuarioModificacion, Date fechaAlta, Date fechaModificacion, Long indEstatus) {
		this.domicilio = domicilio;
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
		this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdPrestadoraServicioDomicilio() {
		return this.idPrestadoraServicioDomicilio;
	}

	public void setIdPrestadoraServicioDomicilio(Long idPrestadoraServicioDomicilio) {
		this.idPrestadoraServicioDomicilio = idPrestadoraServicioDomicilio;
	}


	public Domicilio getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(Domicilio domicilio) {
		this.domicilio = domicilio;
	}


	public Usuario getUsuarioByUsuarioAlta() {
		return this.usuarioByUsuarioAlta;
	}

	public void setUsuarioByUsuarioAlta(Usuario usuarioByUsuarioAlta) {
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
	}


	public Usuario getUsuarioByUsuarioModificacion() {
		return this.usuarioByUsuarioModificacion;
	}

	public void setUsuarioByUsuarioModificacion(Usuario usuarioByUsuarioModificacion) {
		this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
	}


	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}


	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	
	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public PrestadoraServicio getPrestadoraServicio() {
		return prestadoraServicio;
	}

	public void setIdPrestadoraServicio(PrestadoraServicio prestadoraServicio) {
		this.prestadoraServicio = prestadoraServicio;
	}

}
