package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.DefinicionDocumento;
import mx.com.consolida.entity.crm.DocumentoRegistro;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicioDocumento generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio_doctos")
@NamedQueries({ @NamedQuery(name = "PrestadoraServicioDocto.findAll", query = "SELECT c FROM PrestadoraServicioDocto c") })
public class PrestadoraServicioDocto implements java.io.Serializable {


	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_prestadora_servicio_documento")
	private Long idPrestadoraServicioDocumento;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestadora_servicio", nullable = false)
	private PrestadoraServicio prestadoraServicio;


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_definicion_documento", nullable = false)
	private DefinicionDocumento definicionDocumento;

	@Column(name="id_CMS")
	private Long idCMS;

	@Column(name = "nombre_archivo", length = 200)
	private String nombreArchivo;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion")
	private Date fechaModificacion;


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;


	@Column(name = "ind_estatus", nullable = false)
	private String indEstatus;


	public PrestadoraServicioDocto() {
	}


	public Long getIdPrestadoraServicioDocumento() {
		return idPrestadoraServicioDocumento;
	}

	public void setIdPrestadoraServicioDocumento(Long idPrestadoraServicioDocumento) {
		this.idPrestadoraServicioDocumento = idPrestadoraServicioDocumento;
	}

	public PrestadoraServicio getPrestadoraServicio() {
		return prestadoraServicio;
	}

	public void setPrestadoraServicio(PrestadoraServicio prestadoraServicio) {
		this.prestadoraServicio = prestadoraServicio;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public DefinicionDocumento getDefinicionDocumento() {
		return definicionDocumento;
	}

	public void setDefinicionDocumento(DefinicionDocumento definicionDocumento) {
		this.definicionDocumento = definicionDocumento;
	}

	public Long getIdCMS() {
		return idCMS;
	}

	public void setIdCMS(Long idCMS) {
		this.idCMS = idCMS;
	}


	public String getNombreArchivo() {
		return nombreArchivo;
	}


	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}


	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getIndEstatus() {
		return indEstatus;
	}

	public void setIndEstatus(String indEstatus) {
		this.indEstatus = indEstatus;
	}


}
