package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.celula.CelulaPrestadoraServicio;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicio generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio")
@NamedQueries({ @NamedQuery(name = "PrestadoraServicio.findAll", query = "SELECT c FROM PrestadoraServicio c") })
public class PrestadoraServicio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_prestadora_servicio")
	private Long idPrestadoraServicio;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;
	
	@Column(name = "rfc", nullable = false, length = 15)
	private String rfc;
	
	@Column(name = "nombre_corto", nullable = false, length = 45)
	private String nombreCorto;
	
	@Column(name = "razon_social", nullable = false, length = 100)
	private String razonSocial;
	
	@Column(name = "id_consar", length = 50)
	private String id_consar;
	
//	@Column(name = "clave", length = 45)
//	private String clave;
	
	@Column(name = "es_fondo", nullable = false)
	private int esFondo;
	
	@Column(name = "logo")
	private  byte[] logo;
	
	@Column(name = "password_fiel")
	private String passwordFiel;
	
	@Column(name = "password_csd")
	private String passwordCsd;
	
	@Column(name = "nombre_archivo_logotipo")
	private  String nombreArchivoLogotipo;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;
	
	// bi-directional one-to-one association to ClienteTempBitacoraSolicitudes
    @OneToOne(mappedBy = "prestadoraServicio")
    private PrestadoraServicioDomicilio prestadoraServicioDomicilio;
    
 // bi-directional one-to-one association to ClienteTempBitacoraSolicitudes
    @OneToOne(mappedBy = "prestadoraServicio")
    private CelulaPrestadoraServicio celulaPrestadoraServicio;
    
 // bi-directional one-to-one association to ClienteTempBitacoraSolicitudes
    @OneToMany(mappedBy = "prestadoraServicio")
    private List<PrestadoraServicioCuentaBancaria> prestadoraServicioCuentaBancaria;
    
 // bi-directional one-to-one association to ClienteTempBitacoraSolicitudes
    @OneToOne(mappedBy = "prestadoraServicio")
    private PrestadoraServicioDocumento prestadoraServicioDocumento;
    
    @OneToMany(mappedBy = "prestadoraServicio")
    private List<PrestadoraServicioProducto> prestadoraServicioProducto;
    
	@OneToMany(mappedBy = "prestadoraServicio")
	 private List<PrestadoraServicioGiroComercial> prestadoraGiroComercial;
	
	@OneToMany(mappedBy = "prestadoraServicio")
	 private List<PrestadoraServicioStp> prestadoraServicioStp;
    

	public PrestadoraServicio() {
	}
	
	public PrestadoraServicio(Long idPrestadoraServicio) {
		this.idPrestadoraServicio = idPrestadoraServicio;
	}

	public PrestadoraServicio(Usuario usuarioAlta, String rfc, String nombreCorto, String razonSocial, int esFondo,
			Date fechaAlta, Long indEstatus) {
		this.usuarioAlta = usuarioAlta;
		this.rfc = rfc;
		this.nombreCorto = nombreCorto;
		this.razonSocial = razonSocial;
		this.esFondo = esFondo;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public PrestadoraServicio(Usuario usuarioAlta, String rfc, String nombreCorto, String razonSocial, int esFondo,
			Date fechaAlta, Date fechaModificacion, Long indEstatus) {
		this.usuarioAlta = usuarioAlta;
		this.rfc = rfc;
		this.nombreCorto = nombreCorto;
		this.razonSocial = razonSocial;
		this.esFondo = esFondo;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdPrestadoraServicio() {
		return this.idPrestadoraServicio;
	}

	public void setIdPrestadoraServicio(Long idPrestadoraServicio) {
		this.idPrestadoraServicio = idPrestadoraServicio;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	
	public String getNombreCorto() {
		return this.nombreCorto;
	}

	public void setNombreCorto(String nombreCorto) {
		this.nombreCorto = nombreCorto;
	}

	
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	
	public int getEsFondo() {
		return this.esFondo;
	}

	public void setEsFondo(int esFondo) {
		this.esFondo = esFondo;
	}


	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}


	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	
	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public PrestadoraServicioDomicilio getPrestadoraServicioDomicilio() {
		return prestadoraServicioDomicilio;
	}

	public void setPrestadoraServicioDomicilio(PrestadoraServicioDomicilio prestadoraServicioDomicilio) {
		this.prestadoraServicioDomicilio = prestadoraServicioDomicilio;
	}

	public CelulaPrestadoraServicio getCelulaPrestadoraServicio() {
		return celulaPrestadoraServicio;
	}

	public void setCelulaPrestadoraServicio(CelulaPrestadoraServicio celulaPrestadoraServicio) {
		this.celulaPrestadoraServicio = celulaPrestadoraServicio;
	}

	public List<PrestadoraServicioCuentaBancaria> getPrestadoraServicioCuentaBancaria() {
		return prestadoraServicioCuentaBancaria;
	}

	public void setPrestadoraServicioCuentaBancaria(
			List<PrestadoraServicioCuentaBancaria> prestadoraServicioCuentaBancaria) {
		this.prestadoraServicioCuentaBancaria = prestadoraServicioCuentaBancaria;
	}

	public PrestadoraServicioDocumento getPrestadoraServicioDocumento() {
		return prestadoraServicioDocumento;
	}

	public void setPrestadoraServicioDocumento(PrestadoraServicioDocumento prestadoraServicioDocumento) {
		this.prestadoraServicioDocumento = prestadoraServicioDocumento;
	}

	public List<PrestadoraServicioProducto> getPrestadoraServicioProducto() {
		return prestadoraServicioProducto;
	}

	public void setPrestadoraServicioProducto(List<PrestadoraServicioProducto> prestadoraServicioProducto) {
		this.prestadoraServicioProducto = prestadoraServicioProducto;
	}

	public String getId_consar() {
		return id_consar;
	}

	public void setId_consar(String id_consar) {
		this.id_consar = id_consar;
	}

	public List<PrestadoraServicioGiroComercial> getPrestadoraGiroComercial() {
		return prestadoraGiroComercial;
	}

	public void setPrestadoraGiroComercial(List<PrestadoraServicioGiroComercial> prestadoraGiroComercial) {
		this.prestadoraGiroComercial = prestadoraGiroComercial;
	}

//	public String getClave() {
//		return clave;
//	}
//
//	public void setClave(String clave) {
//		this.clave = clave;
//	}

	public byte[] getLogo() {
		return logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	public String getNombreArchivoLogotipo() {
		return nombreArchivoLogotipo;
	}

	public void setNombreArchivoLogotipo(String nombreArchivoLogotipo) {
		this.nombreArchivoLogotipo = nombreArchivoLogotipo;
	}

	public String getPasswordFiel() {
		return passwordFiel;
	}

	public void setPasswordFiel(String passwordFiel) {
		this.passwordFiel = passwordFiel;
	}

	public String getPasswordCsd() {
		return passwordCsd;
	}

	public void setPasswordCsd(String passwordCsd) {
		this.passwordCsd = passwordCsd;
	}

	public List<PrestadoraServicioStp> getPrestadoraServicioStp() {
		return prestadoraServicioStp;
	}

	public void setPrestadoraServicioStp(List<PrestadoraServicioStp> prestadoraServicioStp) {
		this.prestadoraServicioStp = prestadoraServicioStp;
	}
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestadoraServicio")
//	public Set getPrestadoraServicioCuentaBancarias() {
//		return this.prestadoraServicioCuentaBancarias;
//	}
//
//	public void setPrestadoraServicioCuentaBancarias(Set prestadoraServicioCuentaBancarias) {
//		this.prestadoraServicioCuentaBancarias = prestadoraServicioCuentaBancarias;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestadoraServicio")
//	public Set getPrestadoraServicioDocumentos() {
//		return this.prestadoraServicioDocumentos;
//	}
//
//	public void setPrestadoraServicioDocumentos(Set prestadoraServicioDocumentos) {
//		this.prestadoraServicioDocumentos = prestadoraServicioDocumentos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestadoraServicio")
//	public Set getPrestadoraServicioRegistroPatronals() {
//		return this.prestadoraServicioRegistroPatronals;
//	}
//
//	public void setPrestadoraServicioRegistroPatronals(Set prestadoraServicioRegistroPatronals) {
//		this.prestadoraServicioRegistroPatronals = prestadoraServicioRegistroPatronals;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestadoraServicio")
//	public Set getPrestadoraServicioApoderadoLegals() {
//		return this.prestadoraServicioApoderadoLegals;
//	}
//
//	public void setPrestadoraServicioApoderadoLegals(Set prestadoraServicioApoderadoLegals) {
//		this.prestadoraServicioApoderadoLegals = prestadoraServicioApoderadoLegals;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestadoraServicio")
//	public Set getPrestadoraServicioObjetoSocials() {
//		return this.prestadoraServicioObjetoSocials;
//	}
//
//	public void setPrestadoraServicioObjetoSocials(Set prestadoraServicioObjetoSocials) {
//		this.prestadoraServicioObjetoSocials = prestadoraServicioObjetoSocials;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestadoraServicio")
//	public Set getPrestadoraServicioEstatuses() {
//		return this.prestadoraServicioEstatuses;
//	}
//
//	public void setPrestadoraServicioEstatuses(Set prestadoraServicioEstatuses) {
//		this.prestadoraServicioEstatuses = prestadoraServicioEstatuses;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestadoraServicio")
//	public Set getCelulaPrestadoraServicios() {
//		return this.celulaPrestadoraServicios;
//	}
//
//	public void setCelulaPrestadoraServicios(Set celulaPrestadoraServicios) {
//		this.celulaPrestadoraServicios = celulaPrestadoraServicios;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestadoraServicio")
//	public Set getPrestadoraServicioRepresentanteLegals() {
//		return this.prestadoraServicioRepresentanteLegals;
//	}
//
//	public void setPrestadoraServicioRepresentanteLegals(Set prestadoraServicioRepresentanteLegals) {
//		this.prestadoraServicioRepresentanteLegals = prestadoraServicioRepresentanteLegals;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestadoraServicio")
//	public Set getPrestadoraServicioAccionistas() {
//		return this.prestadoraServicioAccionistas;
//	}
//
//	public void setPrestadoraServicioAccionistas(Set prestadoraServicioAccionistas) {
//		this.prestadoraServicioAccionistas = prestadoraServicioAccionistas;
//	}

}
