package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicioDomicilio generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio_producto")
@NamedQueries({ @NamedQuery(name = "PrestadoraServicioProducto.findAll", query = "SELECT c FROM PrestadoraServicioProducto c") })
public class PrestadoraServicioProducto implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_prestadora_servicio_producto")
	private Long idPrestadoraServicioProducto;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestadora_servicio", nullable = false)
	private PrestadoraServicio prestadoraServicio;

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cat_producto_sat", nullable = false)
	private CatGeneral catProductoSat;

	@Column(name = "descripcion_producto_consolida", nullable = false)
	private String descripcionProductoConsolida;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;


	public PrestadoraServicioProducto() {
	}
	public PrestadoraServicioProducto(Long idPrestadoraServicioProducto) {
		this.idPrestadoraServicioProducto= idPrestadoraServicioProducto;
	}

	public Long getIdPrestadoraServicioProducto() {
		return idPrestadoraServicioProducto;
	}

	public void setIdPrestadoraServicioProducto(Long idPrestadoraServicioProducto) {
		this.idPrestadoraServicioProducto = idPrestadoraServicioProducto;
	}

	public PrestadoraServicio getPrestadoraServicio() {
		return prestadoraServicio;
	}

	public void setPrestadoraServicio(PrestadoraServicio prestadoraServicio) {
		this.prestadoraServicio = prestadoraServicio;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public CatGeneral getCatProductoSat() {
		return catProductoSat;
	}

	public void setCatProductoSat(CatGeneral catProductoSat) {
		this.catProductoSat = catProductoSat;
	}

	public String getDescripcionProductoConsolida() {
		return descripcionProductoConsolida;
	}

	public void setDescripcionProductoConsolida(String descripcionProductoConsolida) {
		this.descripcionProductoConsolida = descripcionProductoConsolida;
	}

}
