package mx.com.consolida.entity.prestadoraservicio;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.crm.DocumentoRegistro;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * PrestadoraServicioDocumento generated by hbm2java
 */
@Entity
@Table(name = "prestadora_servicio_documento")
@NamedQueries({ @NamedQuery(name = "PrestadoraServicioDocumento.findAll", query = "SELECT c FROM PrestadoraServicioDocumento c") })
public class PrestadoraServicioDocumento implements java.io.Serializable {


	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_prestadora_servicio_documento")
	private Long idPrestadoraServicioDocumento;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestadora_servicio", nullable = false)
	private PrestadoraServicio prestadoraServicio;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_documento_registro")
	private DocumentoRegistro docuemDocumentoRegistro;

	@Column(name = "id_content_file")
	private Long idContentFile;

	@Column(name = "ruta_documento", length = 45)
	private String rutaDocumento;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion")
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	@Column(name = "nombre_archivo_fiel_cer")
	private String nombreArchivoFielCer;

	@Column(name = "archivo_fiel_cer")
	private byte[] archivoFielCer;

	@Column(name = "nombre_archivo_fiel_key")
	private String nombreArchivoFielKey;

	@Column(name = "archivo_fiel_key")
	private byte[] archivoFielKey;

	@Column(name = "password_fiel")
	private String passwordFiel;

	@Column(name = "nombre_archivo_csd_cer")
	private String nombreArchivoCsdCer;

	@Column(name = "archivo_csd_cer")
	private byte[] archivoCsdCer;

	@Column(name = "nombre_archivo_csd_key")
	private String nombreArchivoCsdKey;

	@Column(name = "archivo_csd_key")
	private byte[] archivoCsdKey;

	@Column(name = "password_csd")
	private String passwordCsd;

	public PrestadoraServicioDocumento() {
	}

	public PrestadoraServicioDocumento(Long idPrestadoraServicioDocumento, PrestadoraServicio prestadoraServicio,
			Usuario usuarioAlta, DocumentoRegistro docuemDocumentoRegistro, Date fechaAlta, Long indEstatus) {
		this.idPrestadoraServicioDocumento = idPrestadoraServicioDocumento;
		this.prestadoraServicio = prestadoraServicio;
		this.usuarioAlta = usuarioAlta;
		this.docuemDocumentoRegistro = docuemDocumentoRegistro;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public PrestadoraServicioDocumento(Long idPrestadoraServicioDocumento, PrestadoraServicio prestadoraServicio,
			Usuario usuarioAlta, DocumentoRegistro docuemDocumentoRegistro, Long idContentFile, String rutaDocumento, Date fechaAlta,
			Date fechaModificacion, Long indEstatus) {
		this.idPrestadoraServicioDocumento = idPrestadoraServicioDocumento;
		this.prestadoraServicio = prestadoraServicio;
		this.usuarioAlta = usuarioAlta;
		this.docuemDocumentoRegistro = docuemDocumentoRegistro;
		this.idContentFile = idContentFile;
		this.rutaDocumento = rutaDocumento;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdPrestadoraServicioDocumento() {
		return idPrestadoraServicioDocumento;
	}

	public void setIdPrestadoraServicioDocumento(Long idPrestadoraServicioDocumento) {
		this.idPrestadoraServicioDocumento = idPrestadoraServicioDocumento;
	}

	public PrestadoraServicio getPrestadoraServicio() {
		return prestadoraServicio;
	}

	public void setPrestadoraServicio(PrestadoraServicio prestadoraServicio) {
		this.prestadoraServicio = prestadoraServicio;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public DocumentoRegistro getDocuemDocumentoRegistro() {
		return docuemDocumentoRegistro;
	}

	public void setDocuemDocumentoRegistro(DocumentoRegistro docuemDocumentoRegistro) {
		this.docuemDocumentoRegistro = docuemDocumentoRegistro;
	}

	public Long getIdContentFile() {
		return idContentFile;
	}

	public void setIdContentFile(Long idContentFile) {
		this.idContentFile = idContentFile;
	}

	public String getRutaDocumento() {
		return rutaDocumento;
	}

	public void setRutaDocumento(String rutaDocumento) {
		this.rutaDocumento = rutaDocumento;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public String getNombreArchivoFielCer() {
		return nombreArchivoFielCer;
	}

	public void setNombreArchivoFielCer(String nombreArchivoFielCer) {
		this.nombreArchivoFielCer = nombreArchivoFielCer;
	}

	public byte[] getArchivoFielCer() {
		return archivoFielCer;
	}

	public void setArchivoFielCer(byte[] archivoFielCer) {
		this.archivoFielCer = archivoFielCer;
	}

	public String getNombreArchivoFielKey() {
		return nombreArchivoFielKey;
	}

	public void setNombreArchivoFielKey(String nombreArchivoFielKey) {
		this.nombreArchivoFielKey = nombreArchivoFielKey;
	}

	public byte[] getArchivoFielKey() {
		return archivoFielKey;
	}

	public void setArchivoFielKey(byte[] archivoFielKey) {
		this.archivoFielKey = archivoFielKey;
	}

	public String getPasswordFiel() {
		return passwordFiel;
	}

	public void setPasswordFiel(String passwordFiel) {
		this.passwordFiel = passwordFiel;
	}

	public String getNombreArchivoCsdCer() {
		return nombreArchivoCsdCer;
	}

	public void setNombreArchivoCsdCer(String nombreArchivoCsdCer) {
		this.nombreArchivoCsdCer = nombreArchivoCsdCer;
	}

	public byte[] getArchivoCsdCer() {
		return archivoCsdCer;
	}

	public void setArchivoCsdCer(byte[] archivoCsdCer) {
		this.archivoCsdCer = archivoCsdCer;
	}

	public String getNombreArchivoCsdKey() {
		return nombreArchivoCsdKey;
	}

	public void setNombreArchivoCsdKey(String nombreArchivoCsdKey) {
		this.nombreArchivoCsdKey = nombreArchivoCsdKey;
	}

	public byte[] getArchivoCsdKey() {
		return archivoCsdKey;
	}

	public void setArchivoCsdKey(byte[] archivoCsdKey) {
		this.archivoCsdKey = archivoCsdKey;
	}

	public String getPasswordCsd() {
		return passwordCsd;
	}

	public void setPasswordCsd(String passwordCsd) {
		this.passwordCsd = passwordCsd;
	}

}
