package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * CatDefinicionDocumento generated by hbm2java
 */
@Entity
@Table(name = "cat_definicion_documento", catalog = "sin")
@NamedQueries({
		@NamedQuery(name = "CatDefinicionDocumento.findAll", query = "SELECT c FROM CatDefinicionDocumento c") })
public class CatDefinicionDocumento implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_cat_definicion_documento")
	private Long idCatDefinicionDocumento;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad_documento", nullable = false)
	private CatGeneral catEntidadDocumento;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Column(name = "clave", nullable = false, length = 15)
	private String clave;

	@Column(name = "descripcion", nullable = false, length = 45)
	private String descripcion;
	private int esRequerido;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false, length = 45)
	private Long indEstatus;

//	private Set documentoRegistros = new HashSet(0);

	public CatDefinicionDocumento() {
	}

	public CatDefinicionDocumento(CatGeneral catEntidadDocumento, Usuario usuarioAlta, Usuario usuarioModificacion,
			String clave, String descripcion, int esRequerido, Date fechaAlta, Date fechaModificacion,
			Long indEstatus) {
		this.catEntidadDocumento = catEntidadDocumento;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.clave = clave;
		this.descripcion = descripcion;
		this.esRequerido = esRequerido;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdCatDefinicionDocumento() {
		return this.idCatDefinicionDocumento;
	}

	public void setIdCatDefinicionDocumento(Long idCatDefinicionDocumento) {
		this.idCatDefinicionDocumento = idCatDefinicionDocumento;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "es_requerido", nullable = false)
	public int getEsRequerido() {
		return this.esRequerido;
	}

	public void setEsRequerido(int esRequerido) {
		this.esRequerido = esRequerido;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "fecha_modificacion", length = 45)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public CatGeneral getCatEntidadDocumento() {
		return catEntidadDocumento;
	}

	public void setCatEntidadDocumento(CatGeneral catEntidadDocumento) {
		this.catEntidadDocumento = catEntidadDocumento;
	}



}
