package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatEntidadFederativa generated by hbm2java
 */
@Entity
@Table(name = "cat_entidad_federativa")
@NamedQueries({ @NamedQuery(name = "CatEntidadFederativa.findAll", query = "SELECT c FROM CatEntidadFederativa c") })
public class CatEntidadFederativa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_entidad_federativa")
	private Long idEntidadFederativa;
	
	@Column(name = "cve_cat_general", length = 45)
	private String cveCatGeneral;
	
	@Column(name = "cve_entidad_federativa", nullable = false, length = 20)
	private String cveEntidadFederativa;
	
	@Column(name = "descripcion_entidad_federativa", nullable = false, length = 60)
	private String descripcionEntidadFederativa;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "usuario_alta", nullable = false, length = 45)
	private Long usuarioAlta;
	
	@Column(name = "usuario_modificacion", length = 45)
	private Long usuarioModificacion;
	
	@Column(name = "ind_estatus")
	private Long indEstatus;
//	private Set medioContactoTemps = new HashSet(0);
//	private Set domicilios = new HashSet(0);

	public CatEntidadFederativa() {
	}

	public CatEntidadFederativa(Long idEntidadFederativa, String cveEntidadFederativa,
			String descripcionEntidadFederativa, Date fechaAlta, Long usuarioAlta) {
		this.idEntidadFederativa = idEntidadFederativa;
		this.cveEntidadFederativa = cveEntidadFederativa;
		this.descripcionEntidadFederativa = descripcionEntidadFederativa;
		this.fechaAlta = fechaAlta;
		this.usuarioAlta = usuarioAlta;
	}

	public CatEntidadFederativa(Long idEntidadFederativa, String cveCatGeneral, String cveEntidadFederativa,
			String descripcionEntidadFederativa, Date fechaAlta, Date fechaModificacion, Long usuarioAlta,
			Long indEstatus) {
		this.idEntidadFederativa = idEntidadFederativa;
		this.cveCatGeneral = cveCatGeneral;
		this.cveEntidadFederativa = cveEntidadFederativa;
		this.descripcionEntidadFederativa = descripcionEntidadFederativa;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.usuarioAlta = usuarioAlta;
		this.indEstatus = indEstatus;
	}


	public Long getIdEntidadFederativa() {
		return this.idEntidadFederativa;
	}

	public void setIdEntidadFederativa(Long idEntidadFederativa) {
		this.idEntidadFederativa = idEntidadFederativa;
	}

	
	public String getCveCatGeneral() {
		return this.cveCatGeneral;
	}

	public void setCveCatGeneral(String cveCatGeneral) {
		this.cveCatGeneral = cveCatGeneral;
	}

	
	public String getCveEntidadFederativa() {
		return this.cveEntidadFederativa;
	}

	public void setCveEntidadFederativa(String cveEntidadFederativa) {
		this.cveEntidadFederativa = cveEntidadFederativa;
	}

	
	public String getDescripcionEntidadFederativa() {
		return this.descripcionEntidadFederativa;
	}

	public void setDescripcionEntidadFederativa(String descripcionEntidadFederativa) {
		this.descripcionEntidadFederativa = descripcionEntidadFederativa;
	}


	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}


	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	
	public Long getUsuarioAlta() {
		return this.usuarioAlta;
	}

	public void setUsuarioAlta(Long usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	
	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public Long getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Long usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}
	
	

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catEntidadFederativa")
//	public Set getMedioContactoTemps() {
//		return this.medioContactoTemps;
//	}
//
//	public void setMedioContactoTemps(Set medioContactoTemps) {
//		this.medioContactoTemps = medioContactoTemps;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catEntidadFederativa")
//	public Set getDomicilios() {
//		return this.domicilios;
//	}
//
//	public void setDomicilios(Set domicilios) {
//		this.domicilios = domicilios;
//	}

}
