package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.seguridad.Usuario;

/**
 * CatFormulaClienHono generated by hbm2java
 */
@Entity
@Table(name = "cat_formula_clien_hono")
@NamedQueries({ @NamedQuery(name = "CatFormulaClienHono.findAll", query = "SELECT c FROM CatFormulaClienHono c") })
public class CatFormulaClienHono implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_cat_formula_clien_hono")
	private Long idCatFormulaClienHono;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Column(name = "clave", nullable = false, length = 45)
	private String clave;

	@Column(name = "descripcion", nullable = false, length = 45)
	private String descripcion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;
//	private Set catFormulaClienHonoDescRelacions = new HashSet(0);

	public CatFormulaClienHono() {
	}

	public CatFormulaClienHono(Usuario usuarioAlta, String clave, String descripcion, Date fechaAlta, Long indEstatus) {
		this.usuarioAlta = usuarioAlta;
		this.clave = clave;
		this.descripcion = descripcion;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public CatFormulaClienHono(Usuario usuarioAlta, String clave, String descripcion, Date fechaAlta,
			Date fechaModificacion, Long indEstatus) {
		this.usuarioAlta = usuarioAlta;
		this.clave = clave;
		this.descripcion = descripcion;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdCatFormulaClienHono() {
		return this.idCatFormulaClienHono;
	}

	public void setIdCatFormulaClienHono(Long idCatFormulaClienHono) {
		this.idCatFormulaClienHono = idCatFormulaClienHono;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

}
