package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.seguridad.Usuario;

/**
 * CatFormulaClienHonoDesc generated by hbm2java
 */
@Entity
@Table(name = "cat_formula_clien_hono_desc")
@NamedQueries({
		@NamedQuery(name = "CatFormulaClienHonoDesc.findAll", query = "SELECT c FROM CatFormulaClienHonoDesc c") })
public class CatFormulaClienHonoDesc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_cat_formula_clien_hono")
	private Long idCatFormulaClienHonoDesc;

	@Column(name = "descripcion", nullable = false, length = 45)
	private String descripcion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;
//	private Set catFormulaClienHonoDescRelacions = new HashSet(0);

	public CatFormulaClienHonoDesc() {
	}

	public CatFormulaClienHonoDesc(String descripcion, Date fechaAlta, Usuario usuarioAlta, Long indEstatus) {
		this.descripcion = descripcion;
		this.fechaAlta = fechaAlta;
		this.usuarioAlta = usuarioAlta;
		this.indEstatus = indEstatus;
	}

	public CatFormulaClienHonoDesc(String descripcion, Date fechaAlta, Date fechaModificacion, Usuario usuarioAlta,
			Long indEstatus) {
		this.descripcion = descripcion;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.usuarioAlta = usuarioAlta;
		this.indEstatus = indEstatus;
		;
	}

	public Long getIdCatFormulaClienHonoDesc() {
		return this.idCatFormulaClienHonoDesc;
	}

	public void setIdCatFormulaClienHonoDesc(Long idCatFormulaClienHonoDesc) {
		this.idCatFormulaClienHonoDesc = idCatFormulaClienHonoDesc;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

}
