package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.seguridad.Usuario;

/**
 * CatFormulaClienHonoDescRelacion generated by hbm2java
 */
@Entity
@Table(name = "cat_formula_clien_hono_desc_relacion")
@NamedQueries({
		@NamedQuery(name = "CatFormulaClienHonoDescRelacion.findAll", query = "SELECT c FROM CatFormulaClienHonoDescRelacion c") })
public class CatFormulaClienHonoDescRelacion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_cat_formula_clien_hono_desc_relacion")
	private Long idCatFormulaClienHonoDescRelacion;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formula_clien_hono", nullable = false)
	private CatFormulaClienHono catFormulaClienHono;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formula_clien_hono_desc", nullable = false)
	private CatFormulaClienHonoDesc catFormulaClienHonoDesc;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;
//	private Set clienteHonoForms = new HashSet(0);
//	private Set clienteFormulaHonorarios = new HashSet(0);

	public CatFormulaClienHonoDescRelacion() {
	}

	public CatFormulaClienHonoDescRelacion(CatFormulaClienHono catFormulaClienHono,
			CatFormulaClienHonoDesc catFormulaClienHonoDesc, Usuario usuarioAlta, Date fechaAlta, Long indEstatus) {
		this.catFormulaClienHono = catFormulaClienHono;
		this.catFormulaClienHonoDesc = catFormulaClienHonoDesc;
		this.usuarioAlta = usuarioAlta;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public CatFormulaClienHonoDescRelacion(CatFormulaClienHono catFormulaClienHono,
			CatFormulaClienHonoDesc catFormulaClienHonoDesc, Usuario usuarioAlta, Date fechaAlta,
			Date fechaModificacion, Long indEstatus) {
		this.catFormulaClienHono = catFormulaClienHono;
		this.catFormulaClienHonoDesc = catFormulaClienHonoDesc;
		this.usuarioAlta = usuarioAlta;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdCatFormulaClienHonoDescRelacion() {
		return this.idCatFormulaClienHonoDescRelacion;
	}

	public void setIdCatFormulaClienHonoDescRelacion(Long idCatFormulaClienHonoDescRelacion) {
		this.idCatFormulaClienHonoDescRelacion = idCatFormulaClienHonoDescRelacion;
	}

	public CatFormulaClienHono getCatFormulaClienHono() {
		return this.catFormulaClienHono;
	}

	public void setCatFormulaClienHono(CatFormulaClienHono catFormulaClienHono) {
		this.catFormulaClienHono = catFormulaClienHono;
	}

	public CatFormulaClienHonoDesc getCatFormulaClienHonoDesc() {
		return this.catFormulaClienHonoDesc;
	}

	public void setCatFormulaClienHonoDesc(CatFormulaClienHonoDesc catFormulaClienHonoDesc) {
		this.catFormulaClienHonoDesc = catFormulaClienHonoDesc;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catFormulaClienHonoDescRelacion")
//	public Set getClienteHonoForms() {
//		return this.clienteHonoForms;
//	}
//
//	public void setClienteHonoForms(Set clienteHonoForms) {
//		this.clienteHonoForms = clienteHonoForms;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catFormulaClienHonoDescRelacion")
//	public Set getClienteFormulaHonorarios() {
//		return this.clienteFormulaHonorarios;
//	}
//
//	public void setClienteFormulaHonorarios(Set clienteFormulaHonorarios) {
//		this.clienteFormulaHonorarios = clienteFormulaHonorarios;
//	}

}
