package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.seguridad.Usuario;

/**
 * CatMunicipios generated by hbm2java
 */
@Entity
@Table(name = "cat_municipios")
@NamedQueries({ @NamedQuery(name = "CatMunicipios.findAll", query = "SELECT c FROM CatMunicipios c") })
public class CatMunicipios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_cat_municipios")
	private Long idCatMunicipios;

	@Column(name = "cve_cat_general", length = 45)
	private String cveCatGeneral;

	@Column(name = "cve_municipio", length = 45)
	private String cveMunicipio;

	@Column(name = "descripcion", length = 45)
	private String descripcion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Column(name = "ind_estatus")
	private Long indEstatus;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_entidad_federativa", nullable = false)
	private CatEntidadFederativa catEntidadFederativa;

	public CatMunicipios() {
	}
	
	public CatMunicipios(Long idCatMunicipios) {
		this.idCatMunicipios = idCatMunicipios;
	}

	public CatMunicipios(String cveCatGeneral, CatEntidadFederativa catEntidadFederativa, String cveMunicipio, String descripcion,
			Date fechaAlta, Usuario usuarioAlta, Long indEstatus) {
		this.cveCatGeneral = cveCatGeneral;
		this.catEntidadFederativa = catEntidadFederativa;
		this.cveMunicipio = cveMunicipio;
		this.descripcion = descripcion;
		this.fechaAlta = fechaAlta;
		this.usuarioAlta = usuarioAlta;
		this.indEstatus = indEstatus;

	}

	public Long getIdCatMunicipios() {
		return idCatMunicipios;
	}

	public void setIdCatMunicipios(Long idCatMunicipios) {
		this.idCatMunicipios = idCatMunicipios;
	}

	public String getCveCatGeneral() {
		return cveCatGeneral;
	}

	public void setCveCatGeneral(String cveCatGeneral) {
		this.cveCatGeneral = cveCatGeneral;
	}

	public CatEntidadFederativa getCatEntidadFederativa() {
		return catEntidadFederativa;
	}

	public void setCatEntidadFederativa(CatEntidadFederativa catEntidadFederativa) {
		this.catEntidadFederativa = catEntidadFederativa;
	}

	public String getCveMunicipio() {
		return cveMunicipio;
	}

	public void setCveMunicipio(String cveMunicipio) {
		this.cveMunicipio = cveMunicipio;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}



	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Long getIndEstatus() {
		return indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

}
