package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.seguridad.Usuario;

/**
 * ClienteDomicilio generated by hbm2java
 */
@Entity
@Table(name = "cliente_domicilio")
@NamedQueries({ @NamedQuery(name = "ClienteDomicilio.findAll", query = "SELECT c FROM ClienteDomicilio c") })
public class ClienteDomicilio implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_cliente_domicilio")
	private Long idClienteDomicilio;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_domicilio", nullable = false)
	private Domicilio domicilio;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	private Cliente cliente;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioByUsuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioByUsuarioModificacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public ClienteDomicilio() {
	}

//	public ClienteDomicilio(Domicilio domicilio, Usuario usuarioByUsuarioAlta, Date fechaAlta, Long indEstatus) {
//		this.domicilio = domicilio;
//		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
//		this.fechaAlta = fechaAlta;
//		this.indEstatus = indEstatus;
//	}
//
//	public ClienteDomicilio(Domicilio domicilio, Usuario usuarioByUsuarioAlta, Usuario usuarioByUsuarioModificacion,
//			Date fechaAlta, Date fechaModificacion, Long indEstatus) {
//		this.domicilio = domicilio;
//		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
//		this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
//		this.fechaAlta = fechaAlta;
//		this.fechaModificacion = fechaModificacion;
//		this.indEstatus = indEstatus;
//	}

	public Long getIdClienteDomicilio() {
		return this.idClienteDomicilio;
	}

	public void setIdClienteDomicilio(Long idClienteDomicilio) {
		this.idClienteDomicilio = idClienteDomicilio;
	}

	public Domicilio getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(Domicilio domicilio) {
		this.domicilio = domicilio;
	}

	public Usuario getUsuarioByUsuarioAlta() {
		return this.usuarioByUsuarioAlta;
	}

	public void setUsuarioByUsuarioAlta(Usuario usuarioByUsuarioAlta) {
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
	}

	public Usuario getUsuarioByUsuarioModificacion() {
		return this.usuarioByUsuarioModificacion;
	}

	public void setUsuarioByUsuarioModificacion(Usuario usuarioByUsuarioModificacion) {
		this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}



}
