package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatEstatus;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * ClienteEstatus generated by hbm2java
 */
@Entity
@Table(name = "cliente_estatus")
@NamedQueries({ @NamedQuery(name = "ClienteEstatus.findAll", query = "SELECT c FROM ClienteEstatus c") })
public class ClienteEstatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_cliente_estatus")
	private Long idClienteEstatus;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	private Cliente cliente;

	@JoinColumn(name="id_estatus", referencedColumnName= "id_estatus")
	@ManyToOne(targetEntity = CatEstatus.class, cascade=CascadeType.ALL)
    private CatEstatus catEstatus;
	
	@Column(name = "observacion", length = 100)
	private String observacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public ClienteEstatus() {
	}

	public ClienteEstatus(Cliente cliente, CatEstatus catEstatus, Date fechaAlta, Usuario usuarioAlta, Long indEstatus) {
		this.cliente = cliente;
		this.catEstatus = catEstatus;
		this.fechaAlta = fechaAlta;
		this.usuarioAlta = usuarioAlta;
		this.indEstatus = indEstatus;
	}

	public ClienteEstatus(Cliente cliente, CatEstatus catEstatus, Date fechaAlta, Date fechaModificacion,
			Usuario usuarioAlta, Long indEstatus) {
		this.cliente = cliente;
		this.catEstatus = catEstatus;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.usuarioAlta = usuarioAlta;
		this.indEstatus = indEstatus;
	}

	public Long getIdClienteEstatus() {
		return this.idClienteEstatus;
	}

	public void setIdClienteEstatus(Long idClienteEstatus) {
		this.idClienteEstatus = idClienteEstatus;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}



	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}


	public CatEstatus getCatEstatus() {
		return catEstatus;
	}

	public void setCatEstatus(CatEstatus catEstatus) {
		this.catEstatus = catEstatus;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public String getObservacion() {
		return observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

}
