package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * ClienteActProfSat generated by hbm2java
 */
@Entity
@Table(name = "cliente_act_prof_sat")
@NamedQueries({ @NamedQuery(name = "ClienteActProfSat.findAll", query = "SELECT c FROM ClienteActProfSat c") })
public class ClienteActProfSat implements java.io.Serializable {


	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_cliente_act_prof_sat")
	private Long idClienteActProfSat;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_act_prof_sat", nullable = false)
	private CatGeneral catActProfSat;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	private Cliente cliente;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public ClienteActProfSat() {
	}

	public ClienteActProfSat(Long idClienteActProfSat, CatGeneral catActProfSat, Cliente cliente, Usuario usuarioAlta,
			Usuario usuarioModificacion, Date fechaAlta, Long indEstatus) {
		this.idClienteActProfSat = idClienteActProfSat;
		this.catActProfSat = catActProfSat;
		this.cliente = cliente;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public ClienteActProfSat(Long idClienteActProfSat, CatGeneral catActProfSat, Cliente cliente, Usuario usuarioAlta,
			Usuario usuarioModificacion, Date fechaAlta, Date fechaModificacion, Long indEstatus) {
		this.idClienteActProfSat = idClienteActProfSat;
		this.catActProfSat = catActProfSat;
		this.cliente = cliente;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdClienteActProfSat() {
		return this.idClienteActProfSat;
	}

	public void setIdClienteActProfSat(Long idClienteActProfSat) {
		this.idClienteActProfSat = idClienteActProfSat;
	}

	public CatGeneral getCatActProfSat() {
		return catActProfSat;
	}

	public void setCatActProfSat(CatGeneral catActProfSat) {
		this.catActProfSat = catActProfSat;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

}
