package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * ClienteApoderadoLegalPoderNotarial generated by hbm2java
 */
@Entity
@Table(name = "cliente_apoderado_legal_poder_notarial")
@NamedQueries({
		@NamedQuery(name = "ClienteApoderadoLegalPoderNotarial.findAll", query = "SELECT c FROM ClienteApoderadoLegalPoderNotarial c") })
public class ClienteApoderadoLegalPoderNotarial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_cliente_apoderado_legal_poder_notarial", unique = true, nullable = false)
	private Long idClienteApoderadoLegalPoderNotarial;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_poder_notarial", nullable = false)
	private CatGeneral catPoderNotarial;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente_apoderado_legal", nullable = false)
	private ClienteApoderadoLegal clienteApoderadoLegal;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_Modificacion")
	private Usuario usuarioModificacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public ClienteApoderadoLegalPoderNotarial() {
	}

	public ClienteApoderadoLegalPoderNotarial(CatGeneral catPoderNotarial, ClienteApoderadoLegal clienteApoderadoLegal,
			Usuario usuarioAlta, Usuario usuarioModificacion, Date fechaAlta, Long indEstatus) {
		this.catPoderNotarial = catPoderNotarial;
		this.clienteApoderadoLegal = clienteApoderadoLegal;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public ClienteApoderadoLegalPoderNotarial(CatGeneral catPoderNotarial, ClienteApoderadoLegal clienteApoderadoLegal,
			Usuario usuarioAlta, Usuario usuarioModificacion, Date fechaAlta, Date fechaModificacion, Long indEstatus) {
		this.catPoderNotarial = catPoderNotarial;
		this.clienteApoderadoLegal = clienteApoderadoLegal;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdClienteApoderadoLegalPoderNotarial() {
		return this.idClienteApoderadoLegalPoderNotarial;
	}

	public void setIdClienteApoderadoLegalPoderNotarial(Long idClienteApoderadoLegalPoderNotarial) {
		this.idClienteApoderadoLegalPoderNotarial = idClienteApoderadoLegalPoderNotarial;
	}

	public CatGeneral getCatPoderNotarial() {
		return catPoderNotarial;
	}

	public void setCatPoderNotarial(CatGeneral catPoderNotarial) {
		this.catPoderNotarial = catPoderNotarial;
	}

	public ClienteApoderadoLegal getClienteApoderadoLegal() {
		return this.clienteApoderadoLegal;
	}

	public void setClienteApoderadoLegal(ClienteApoderadoLegal clienteApoderadoLegal) {
		this.clienteApoderadoLegal = clienteApoderadoLegal;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

}
