package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * ClienteCuentaBancaria generated by hbm2java
 */
@Entity
@Table(name = "cliente_cuenta_bancaria")
@NamedQueries({ @NamedQuery(name = "ClienteCuentaBancaria.findAll", query = "SELECT c FROM ClienteCuentaBancaria c") })
public class ClienteCuentaBancaria implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_cliente_cuenta_bancaria")
	private Long idClienteCuentaBancaria;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_banco", nullable = false)
	private CatGeneral catBanco;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	private Cliente cliente;

	@Column(name = "numero_cuenta",  length = 30)
	private String numeroCuenta;

	@Column(name = "clabe_interbancaria",  length = 30)
	private String clabeInterbancaria;

	@Column(name = "numero_referencia", length = 30)
	private String numeroReferencia;

	@Column(name = "es_principal", nullable = false)
	private int esPrincipal;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_cuenta", nullable = false)
	private CatGeneral catTipoCuenta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public ClienteCuentaBancaria() {
	}

	public ClienteCuentaBancaria(Long idClienteCuentaBancaria, CatGeneral catBanco, Cliente cliente,
			Usuario usuarioAlta, Usuario usuarioModificacion, String numeroCuenta, String clabeInterbancaria,
			Date fechaAlta, Long indEstatus) {
		this.idClienteCuentaBancaria = idClienteCuentaBancaria;
		this.catBanco = catBanco;
		this.cliente = cliente;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.numeroCuenta = numeroCuenta;
		this.clabeInterbancaria = clabeInterbancaria;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public ClienteCuentaBancaria(Long idClienteCuentaBancaria, CatGeneral catBanco, Cliente cliente,
			Usuario usuarioAlta, Usuario usuarioModificacion, String numeroCuenta, String clabeInterbancaria,
			Date fechaAlta, Date fechaModificacion, Long indEstatus) {
		this.idClienteCuentaBancaria = idClienteCuentaBancaria;
		this.catBanco = catBanco;
		this.cliente = cliente;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.numeroCuenta = numeroCuenta;
		this.clabeInterbancaria = clabeInterbancaria;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdClienteCuentaBancaria() {
		return this.idClienteCuentaBancaria;
	}

	public void setIdClienteCuentaBancaria(Long idClienteCuentaBancaria) {
		this.idClienteCuentaBancaria = idClienteCuentaBancaria;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(String numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	public String getClabeInterbancaria() {
		return this.clabeInterbancaria;
	}

	public void setClabeInterbancaria(String clabeInterbancaria) {
		this.clabeInterbancaria = clabeInterbancaria;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public CatGeneral getCatBanco() {
		return catBanco;
	}

	public void setCatBanco(CatGeneral catBanco) {
		this.catBanco = catBanco;
	}

	public String getNumeroReferencia() {
		return numeroReferencia;
	}

	public void setNumeroReferencia(String numeroReferencia) {
		this.numeroReferencia = numeroReferencia;
	}

	public int getEsPrincipal() {
		return esPrincipal;
	}

	public void setEsPrincipal(int esPrincipal) {
		this.esPrincipal = esPrincipal;
	}

	public CatGeneral getCatTipoCuenta() {
		return catTipoCuenta;
	}

	public void setCatTipoCuenta(CatGeneral catTipoCuenta) {
		this.catTipoCuenta = catTipoCuenta;
	}

}
