package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * ClienteApoderadoLegalFacultad generated by hbm2java
 */
@Entity
@Table(name = "cliente_apoderado_legal_facultad")
@NamedQueries({ @NamedQuery(name = "ClienteApoderadoLegalFacultad.findAll", query = "SELECT c FROM ClienteApoderadoLegalFacultad c") })
public class ClienteApoderadoLegalFacultad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_cliente_apoderado_legal_facultad", unique = true, nullable = false)
	private Long idClienteApoderadoLegalFacultad;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_facultad", nullable = false)
	private CatGeneral catFacultad;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente_apoderado_legal", nullable = false)
	private ClienteApoderadoLegal clienteApoderadoLegal;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public ClienteApoderadoLegalFacultad() {
	}

	public ClienteApoderadoLegalFacultad(CatGeneral catFacultad, ClienteApoderadoLegal clienteApoderadoLegal,
			Usuario usuarioAlta, Usuario usuarioModificacion, Date fechaAlta, Long indEstatus) {
		this.catFacultad = catFacultad;
		this.clienteApoderadoLegal = clienteApoderadoLegal;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public ClienteApoderadoLegalFacultad(CatGeneral catFacultad, ClienteApoderadoLegal clienteApoderadoLegal,
			Usuario usuarioAlta, Usuario usuarioModificacion, Date fechaAlta, Date fechaModificacion, Long indEstatus) {
		this.catFacultad = catFacultad;
		this.clienteApoderadoLegal = clienteApoderadoLegal;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdClienteApoderadoLegalFacultad() {
		return this.idClienteApoderadoLegalFacultad;
	}

	public void setIdClienteApoderadoLegalFacultad(Long idClienteApoderadoLegalFacultad) {
		this.idClienteApoderadoLegalFacultad = idClienteApoderadoLegalFacultad;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public ClienteApoderadoLegal getClienteApoderadoLegal() {
		return this.clienteApoderadoLegal;
	}

	public void setClienteApoderadoLegal(ClienteApoderadoLegal clienteApoderadoLegal) {
		this.clienteApoderadoLegal = clienteApoderadoLegal;
	}


	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	
	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

}
