package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.DefinicionDocumento;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * ClienteApoderadoLegalDocumento generated by hbm2java
 */
@Entity
@Table(name = "cliente_apoderado_legal_documento")
@NamedQueries({ @NamedQuery(name = "ClienteApoderadoLegalDocumento.findAll", query = "SELECT c FROM ClienteApoderadoLegalDocumento c") })
public class ClienteApoderadoLegalDocumento implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_cliente_apoderado_legal_documento")
	private Long idClienteApoderadoLegalDocumento;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente_apoderado_legal", nullable = false)
	private ClienteApoderadoLegal clienteApoderadoLegal;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_definicion_documento", nullable = false)
	private DefinicionDocumento definicionDocumento;
	
	@Column(name="id_CMS")
	private Long idCMS;
	
	@Column(name = "nombre_archivo", length = 250)
	private String nombreArchivo;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "ind_estatus", nullable = false)
	private String indEstatus;

	public ClienteApoderadoLegalDocumento() {
	}

	public ClienteApoderadoLegalDocumento(Long idClienteApoderadoLegalDocumento) {
		this.idClienteApoderadoLegalDocumento = idClienteApoderadoLegalDocumento;
	}

	public Long getIdClienteApoderadoLegalDocumento() {
		return idClienteApoderadoLegalDocumento;
	}

	public void setIdClienteApoderadoLegalDocumento(Long idClienteApoderadoLegalDocumento) {
		this.idClienteApoderadoLegalDocumento = idClienteApoderadoLegalDocumento;
	}

	public ClienteApoderadoLegal getClienteApoderadoLegal() {
		return clienteApoderadoLegal;
	}

	public void setClienteApoderadoLegal(ClienteApoderadoLegal clienteApoderadoLegal) {
		this.clienteApoderadoLegal = clienteApoderadoLegal;
	}

	public DefinicionDocumento getDefinicionDocumento() {
		return definicionDocumento;
	}

	public void setDefinicionDocumento(DefinicionDocumento definicionDocumento) {
		this.definicionDocumento = definicionDocumento;
	}

	public Long getIdCMS() {
		return idCMS;
	}

	public void setIdCMS(Long idCMS) {
		this.idCMS = idCMS;
	}

	public String getNombreArchivo() {
		return nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getIndEstatus() {
		return indEstatus;
	}

	public void setIndEstatus(String indEstatus) {
		this.indEstatus = indEstatus;
	}

}
