package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.seguridad.Usuario;

/**
 * ClienteMedioContacto generated by hbm2java
 */
@Entity
@Table(name = "cliente_medio_contacto")
@NamedQueries({ @NamedQuery(name = "ClienteMedioContacto.findAll", query = "SELECT c FROM ClienteMedioContacto c") })
public class ClienteMedioContacto implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_cliente_medio_contacto")
	private Long idClienteMedioContacto;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	private Cliente cliente;

	@Column(name = "nombre", nullable = false, length = 45)
	private String nombre;

	@Column(name = "apellido_paterno", nullable = false, length = 45)
	private String apellidoPaterno;

	@Column(name = "apellido_materno", length = 45)
	private String apellidoMaterno;

	@Column(name = "correo", nullable = false, length = 45)
	private String correo;

	@Column(name = "telefono", nullable = false, length = 45)
	private String telefono;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	@Column(name = "es_ceo")
	private Integer esCeo;


	@Column(name = "fecha_nacimiento")
	private Date fechaNacimiento;

	public ClienteMedioContacto() {
	}

	public ClienteMedioContacto(Cliente cliente, String nombre, String apellidoPaterno, String apellidoMaterno,
			String correo, String telefono, Date fechaAlta, Usuario usuarioAlta, Long indEstatus) {
		this.cliente = cliente;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.correo = correo;
		this.telefono = telefono;
		this.fechaAlta = fechaAlta;
		this.usuarioAlta = usuarioAlta;
		this.indEstatus = indEstatus;
	}

	public ClienteMedioContacto(Long idClienteMedioContacto,Cliente cliente, String nombre, String apellidoPaterno, String apellidoMaterno,
			String correo, String telefono, Date fechaAlta, Date fechaModificacion, Usuario usuarioAlta, Long indEstatus) {
		this.idClienteMedioContacto= idClienteMedioContacto;
		this.cliente = cliente;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.correo = correo;
		this.telefono = telefono;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.usuarioAlta = usuarioAlta;
		this.indEstatus = indEstatus;
	}

	public Long getIdClienteMedioContacto() {
		return this.idClienteMedioContacto;
	}

	public void setIdClienteMedioContacto(Long idClienteMedioContacto) {
		this.idClienteMedioContacto = idClienteMedioContacto;
	}


	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}


	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}


	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}


	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}


	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}


	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}


	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}


	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public Integer getEsCeo() {
		return esCeo;
	}

	public void setEsCeo(Integer esCeo) {
		this.esCeo = esCeo;
	}

	public Date getFechaNacimiento() {
		return fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

}
