package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.CatGrupo;
import mx.com.consolida.entity.ClienteTemp;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", uniqueConstraints = @UniqueConstraint(columnNames = "rfc"))
@NamedQueries({ @NamedQuery(name = "Cliente.findAll", query = "SELECT c FROM Cliente c") })
public class Cliente implements java.io.Serializable {


	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_cliente")
	private Long idCliente;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_persona", nullable = false)
	private CatGeneral catTipoPersona;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cat_tipo_pago")
	private CatGeneral catTipoPago;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cat_categoria")
	private CatGeneral catCategoria;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cat_regimen_fiscal")
	private CatGeneral catRegimenFiscal;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente_temp")
	private ClienteTemp clienteTemp;

	@Column(name = "rfc", unique = true, length = 20)
	private String rfc;

	@Column(name = "razon_social", length = 100)
	private String razonSocial;

	@Column(name = "nombre", length = 50)
	private String nombre;

	@Column(name = "apellido_paterno", length = 50)
	private String apellidoPaterno;

	@Column(name = "apellido_materno", length = 50)
	private String apellidoMaterno;

	@Column(name = "nombre_comercial", length = 100)
	private String nombreComercial;
	
	@Column(name = "es_activo")
	private Boolean esActivo;

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_constitucion_empresa", length = 10)
	private Date fechaConstitucionEmpresa;

	@Column(name = "cve_registro_patronal", length = 45)
	private String cveRegistroPatronal;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cat_grupo", nullable = false)
	private CatGrupo catGrupo;
	
    @Column(name = "id_cat_giro_comercial")
    private Long idCatGiroComercial;
    
    @Column(name = "id_cat_sub_giro_comercial")
    private Long idSubCatGiroComercial;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;
	
	@Column(name = "prefijo_stp", length = 44)
	private String prefijoSTP;
	
	@Column(name = "actividad_economica_final", length = 250)
	private String actividadEconomicaFinal;
	 
	@OneToMany(mappedBy = "cliente")
	 private List<ClienteDomicilio> clienteDomicilio;
	
	@OneToMany(mappedBy = "cliente")
	 private List<ClienteMedioContacto> clienteMedioContacto;
		
	@OneToMany(mappedBy = "cliente")
	 private List<ClienteCuentaBancaria> clienteCuentaBancaria;
	
	@OneToMany(mappedBy = "cliente")
	 private List<ClienteGiroComercial> ClienteGiroComercial;
	
	@OneToMany(mappedBy = "cliente")
	 private List<ClienteServicio> clienteProductos;

	public Cliente() {
	}
	
	public Cliente(Long idCliente) {
		this.idCliente = idCliente;
	}

	public Cliente(CatGeneral catTipoPersona, Usuario usuarioAlta, Usuario usuarioModificacion, String rfc, Date fechaAlta,
			Long indEstatus) {
		this.catTipoPersona = catTipoPersona;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.rfc = rfc;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public Cliente(CatGeneral catTipoPersona, 
			ClienteTemp clienteTemp, Usuario usuarioAlta, Usuario usuarioModificacion, String rfc, String razonSocial,
			String nombre, String apellidoPaterno, String apellidoMaterno, String nombreComercial,
			Date fechaConstitucionEmpresa, String cveRegistroPatronal,Date fechaAlta,
			Date fechaModificacion, Long indEstatus) {
		this.catTipoPersona = catTipoPersona;
		this.clienteTemp = clienteTemp;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.rfc = rfc;
		this.razonSocial = razonSocial;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.nombreComercial = nombreComercial;
		this.fechaConstitucionEmpresa = fechaConstitucionEmpresa;
		this.cveRegistroPatronal = cveRegistroPatronal;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public Long getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Long idCliente) {
		this.idCliente = idCliente;
	}


	public CatGeneral getCatTipoPersona() {
		return catTipoPersona;
	}

	public void setCatTipoPersona(CatGeneral catTipoPersona) {
		this.catTipoPersona = catTipoPersona;
	}

	public ClienteTemp getClienteTemp() {
		return this.clienteTemp;
	}

	public void setClienteTemp(ClienteTemp clienteTemp) {
		this.clienteTemp = clienteTemp;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getNombreComercial() {
		return this.nombreComercial;
	}

	public void setNombreComercial(String nombreComercial) {
		this.nombreComercial = nombreComercial;
	}

	public Date getFechaConstitucionEmpresa() {
		return this.fechaConstitucionEmpresa;
	}

	public void setFechaConstitucionEmpresa(Date fechaConstitucionEmpresa) {
		this.fechaConstitucionEmpresa = fechaConstitucionEmpresa;
	}

	public String getCveRegistroPatronal() {
		return this.cveRegistroPatronal;
	}

	public void setCveRegistroPatronal(String cveRegistroPatronal) {
		this.cveRegistroPatronal = cveRegistroPatronal;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

	public CatGrupo getCatGrupo() {
		return catGrupo;
	}

	public void setCatGrupo(CatGrupo catGrupo) {
		this.catGrupo = catGrupo;
	}

	public List<ClienteDomicilio> getClienteDomicilio() {
		return clienteDomicilio;
	}

	public void setClienteDomicilio(List<ClienteDomicilio> clienteDomicilio) {
		this.clienteDomicilio = clienteDomicilio;
	}

	public CatGeneral getCatTipoPago() {
		return catTipoPago;
	}

	public void setCatTipoPago(CatGeneral catTipoPago) {
		this.catTipoPago = catTipoPago;
	}

	public Long getIdCatGiroComercial() {
		return idCatGiroComercial;
	}

	public void setIdCatGiroComercial(Long idCatGiroComercial) {
		this.idCatGiroComercial = idCatGiroComercial;
	}

	public Long getIdSubCatGiroComercial() {
		return idSubCatGiroComercial;
	}

	public void setIdSubCatGiroComercial(Long idSubCatGiroComercial) {
		this.idSubCatGiroComercial = idSubCatGiroComercial;
	}

	public List<ClienteCuentaBancaria> getClienteCuentaBancaria() {
		return clienteCuentaBancaria;
	}

	public void setClienteCuentaBancaria(List<ClienteCuentaBancaria> clienteCuentaBancaria) {
		this.clienteCuentaBancaria = clienteCuentaBancaria;
	}

	public List<ClienteGiroComercial> getClienteGiroComercial() {
		return ClienteGiroComercial;
	}

	public void setClienteGiroComercial(List<ClienteGiroComercial> clienteGiroComercial) {
		ClienteGiroComercial = clienteGiroComercial;
	}

	public List<ClienteServicio> getClienteProductos() {
		return clienteProductos;
	}

	public void setClienteProductos(List<ClienteServicio> clienteProductos) {
		this.clienteProductos = clienteProductos;
	}

	public List<ClienteMedioContacto> getClienteMedioContacto() {
		return clienteMedioContacto;
	}

	public void setClienteMedioContacto(List<ClienteMedioContacto> clienteMedioContacto) {
		this.clienteMedioContacto = clienteMedioContacto;
	}

	public CatGeneral getCatCategoria() {
		return catCategoria;
	}

	public void setCatCategoria(CatGeneral catCategoria) {
		this.catCategoria = catCategoria;
	}

	public Boolean getEsActivo() {
		return esActivo;
	}

	public void setEsActivo(Boolean esActivo) {
		this.esActivo = esActivo;
	}

	public CatGeneral getCatRegimenFiscal() {
		return catRegimenFiscal;
	}

	public void setCatRegimenFiscal(CatGeneral catRegimenFiscal) {
		this.catRegimenFiscal = catRegimenFiscal;
	}

	public String getPrefijoSTP() {
		return prefijoSTP;
	}

	public void setPrefijoSTP(String prefijoSTP) {
		this.prefijoSTP = prefijoSTP;
	}

	public String getActividadEconomicaFinal() {
		return actividadEconomicaFinal;
	}

	public void setActividadEconomicaFinal(String actividadEconomicaFinal) {
		this.actividadEconomicaFinal = actividadEconomicaFinal;
	}


}
