package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Persona;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * ClienteApoderadoLegal generated by hbm2java
 */
@Entity
@Table(name = "cliente_apoderado_legal")
@NamedQueries({ @NamedQuery(name = "ClienteApoderadoLegal.findAll", query = "SELECT c FROM ClienteApoderadoLegal c") })
public class ClienteApoderadoLegal implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_cliente_apoderado_legal")
	private Long idClienteApoderadoLegal;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	private Cliente cliente;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	private Persona persona;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cat_facultad", nullable = false)
	private CatGeneral catFacultad;

	@Column(name = "poder_notarial", nullable = false)
	private String poderNotarial;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;


	public ClienteApoderadoLegal() {
	}

	public ClienteApoderadoLegal(Long idClienteApoderadoLegal) {
		this.idClienteApoderadoLegal= idClienteApoderadoLegal;
	}

	public Long getIdClienteApoderadoLegal() {
		return idClienteApoderadoLegal;
	}


	public void setIdClienteApoderadoLegal(Long idClienteApoderadoLegal) {
		this.idClienteApoderadoLegal = idClienteApoderadoLegal;
	}


	public Cliente getCliente() {
		return cliente;
	}


	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}


	public Persona getPersona() {
		return persona;
	}


	public void setPersona(Persona persona) {
		this.persona = persona;
	}


	public CatGeneral getCatFacultad() {
		return catFacultad;
	}


	public void setCatFacultad(CatGeneral catFacultad) {
		this.catFacultad = catFacultad;
	}


	public String getPoderNotarial() {
		return poderNotarial;
	}


	public void setPoderNotarial(String poderNotarial) {
		this.poderNotarial = poderNotarial;
	}


	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}


	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}


	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}


	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}


	public Date getFechaAlta() {
		return fechaAlta;
	}


	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}


	public Date getFechaModificacion() {
		return fechaModificacion;
	}


	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}


	public Long getIndEstatus() {
		return indEstatus;
	}


	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}



}
