package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.seguridad.Usuario;

/**
 * DocumentoRegistro generated by hbm2java
 */
@Entity
@Table(name = "documento_registro")
@NamedQueries({ @NamedQuery(name = "DocumentoRegistro.findAll", query = "SELECT c FROM DocumentoRegistro c") })
public class DocumentoRegistro implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_documento_registro")
	private Long idDocumentoRegistro;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_definicion_documento", nullable = false)
	private CatDefinicionDocumento catDefinicionDocumento;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioByUsuarioModificacion;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioByUsuarioAlta;

	@Column(name = "id_content_file", nullable = false, length = 45)
	private String idContentFile;

	@Column(name = "ruta", nullable = false, length = 45)
	private String ruta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;
//	private Set prestadoraServicioApoderadoLegalDocumentos = new HashSet(0);
//	private Set clienteApoderadoLegalDocumentos = new HashSet(0);
//	private Set prestadoraServicioAccionistaDocumentos = new HashSet(0);
//	private Set colaboradorDocumentos = new HashSet(0);
//	private Set prestadoraServicioRepresentanteLegalDocumentos = new HashSet(0);

	public DocumentoRegistro() {
	}

	public DocumentoRegistro(Long idDocumentoRegistro, CatDefinicionDocumento catDefinicionDocumento,
			Usuario usuarioByUsuarioAlta, String idContentFile, String ruta, Date fechaAlta, Date fechaModificacion, Long indEstatus) {
		this.idDocumentoRegistro = idDocumentoRegistro;
		this.catDefinicionDocumento = catDefinicionDocumento;
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
		this.idContentFile = idContentFile;
		this.ruta = ruta;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}

	public DocumentoRegistro(Long idDocumentoRegistro, CatDefinicionDocumento catDefinicionDocumento,
			Usuario usuarioByUsuarioModificacion, Usuario usuarioByUsuarioAlta, String idContentFile, String ruta,
			Date fechaAlta, Date fechaModificacion, Long indEstatus
//			, Set prestadoraServicioApoderadoLegalDocumentos,
//			Set clienteApoderadoLegalDocumentos, Set prestadoraServicioAccionistaDocumentos, Set colaboradorDocumentos,
//			Set prestadoraServicioRepresentanteLegalDocumentos
			) {
		this.idDocumentoRegistro = idDocumentoRegistro;
		this.catDefinicionDocumento = catDefinicionDocumento;
		this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
		this.idContentFile = idContentFile;
		this.ruta = ruta;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
//		this.prestadoraServicioApoderadoLegalDocumentos = prestadoraServicioApoderadoLegalDocumentos;
//		this.clienteApoderadoLegalDocumentos = clienteApoderadoLegalDocumentos;
//		this.prestadoraServicioAccionistaDocumentos = prestadoraServicioAccionistaDocumentos;
//		this.colaboradorDocumentos = colaboradorDocumentos;
//		this.prestadoraServicioRepresentanteLegalDocumentos = prestadoraServicioRepresentanteLegalDocumentos;
	}


	public Long getIdDocumentoRegistro() {
		return this.idDocumentoRegistro;
	}

	public void setIdDocumentoRegistro(Long idDocumentoRegistro) {
		this.idDocumentoRegistro = idDocumentoRegistro;
	}


	public CatDefinicionDocumento getCatDefinicionDocumento() {
		return this.catDefinicionDocumento;
	}

	public void setCatDefinicionDocumento(CatDefinicionDocumento catDefinicionDocumento) {
		this.catDefinicionDocumento = catDefinicionDocumento;
	}


	public Usuario getUsuarioByUsuarioModificacion() {
		return this.usuarioByUsuarioModificacion;
	}

	public void setUsuarioByUsuarioModificacion(Usuario usuarioByUsuarioModificacion) {
		this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
	}


	public Usuario getUsuarioByUsuarioAlta() {
		return this.usuarioByUsuarioAlta;
	}

	public void setUsuarioByUsuarioAlta(Usuario usuarioByUsuarioAlta) {
		this.usuarioByUsuarioAlta = usuarioByUsuarioAlta;
	}

	public String getIdContentFile() {
		return this.idContentFile;
	}

	public void setIdContentFile(String idContentFile) {
		this.idContentFile = idContentFile;
	}

	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}


	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}


	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}


	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoRegistro")
//	public Set getPrestadoraServicioApoderadoLegalDocumentos() {
//		return this.prestadoraServicioApoderadoLegalDocumentos;
//	}
//
//	public void setPrestadoraServicioApoderadoLegalDocumentos(Set prestadoraServicioApoderadoLegalDocumentos) {
//		this.prestadoraServicioApoderadoLegalDocumentos = prestadoraServicioApoderadoLegalDocumentos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoRegistro")
//	public Set getClienteApoderadoLegalDocumentos() {
//		return this.clienteApoderadoLegalDocumentos;
//	}
//
//	public void setClienteApoderadoLegalDocumentos(Set clienteApoderadoLegalDocumentos) {
//		this.clienteApoderadoLegalDocumentos = clienteApoderadoLegalDocumentos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoRegistro")
//	public Set getPrestadoraServicioAccionistaDocumentos() {
//		return this.prestadoraServicioAccionistaDocumentos;
//	}
//
//	public void setPrestadoraServicioAccionistaDocumentos(Set prestadoraServicioAccionistaDocumentos) {
//		this.prestadoraServicioAccionistaDocumentos = prestadoraServicioAccionistaDocumentos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoRegistro")
//	public Set getColaboradorDocumentos() {
//		return this.colaboradorDocumentos;
//	}
//
//	public void setColaboradorDocumentos(Set colaboradorDocumentos) {
//		this.colaboradorDocumentos = colaboradorDocumentos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentoRegistro")
//	public Set getPrestadoraServicioRepresentanteLegalDocumentos() {
//		return this.prestadoraServicioRepresentanteLegalDocumentos;
//	}
//
//	public void setPrestadoraServicioRepresentanteLegalDocumentos(Set prestadoraServicioRepresentanteLegalDocumentos) {
//		this.prestadoraServicioRepresentanteLegalDocumentos = prestadoraServicioRepresentanteLegalDocumentos;
//	}

}
