package mx.com.consolida.entity.crm;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final


import java.util.Date;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.CatGeneral;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * Domicilio generated by hbm2java
 */
@Entity
@Table(name = "domicilio")
@NamedQueries({ @NamedQuery(name = "Domicilio.findAll", query = "SELECT c FROM Domicilio c") })
public class Domicilio implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_domicilio")
	private Long idDomicilio;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_entidad_federativa", nullable = false)
	private CatEntidadFederativa catEntidadFederativa;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_domicilio")
	private CatGeneral catTipoDomicilio;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio", nullable = false)
	private CatMunicipios catMunicipios;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioByUsuarioModificacion;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usaurio_alta", nullable = false)
	private Usuario usuarioByUsaurioAlta;

	@Column(name = "calle", length = 100)
	private String calle;

	@Column(name = "numero_exterior", length = 10)
	private String numeroExterior;

	@Column(name = "numero_interior", length = 10)
	private String numeroInterior;

	@Column(name = "colonia", length = 100)
	private String colonia;

	@Column(name = "codigo_postal", nullable = false, length = 20)
	private String codigoPostal;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;

	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;
//	private Set clienteMedioContactoDomicilios = new HashSet(0);
//	private Set prestadoraServicioRegistroPatronalDomicilios = new HashSet(0);
//	private Set prestadoraServicioDomicilios = new HashSet(0);
//	private Set clienteDomicilios = new HashSet(0);
//	private Set prestadoraServicioAccionistaDomicilios = new HashSet(0);

	public Domicilio() {
	}

	public Domicilio(Long idDomicilio) {
		this.idDomicilio = idDomicilio;
	}

	public Long getIdDomicilio() {
		return this.idDomicilio;
	}

	public void setIdDomicilio(Long idDomicilio) {
		this.idDomicilio = idDomicilio;
	}


	public CatEntidadFederativa getCatEntidadFederativa() {
		return this.catEntidadFederativa;
	}

	public void setCatEntidadFederativa(CatEntidadFederativa catEntidadFederativa) {
		this.catEntidadFederativa = catEntidadFederativa;
	}

	public CatGeneral getCatTipoDomicilio() {
		return catTipoDomicilio;
	}

	public void setCatTipoDomicilio(CatGeneral catTipoDomicilio) {
		this.catTipoDomicilio = catTipoDomicilio;
	}

	public CatMunicipios getCatMunicipios() {
		return this.catMunicipios;
	}

	public void setCatMunicipios(CatMunicipios catMunicipios) {
		this.catMunicipios = catMunicipios;
	}


	public Usuario getUsuarioByUsuarioModificacion() {
		return this.usuarioByUsuarioModificacion;
	}

	public void setUsuarioByUsuarioModificacion(Usuario usuarioByUsuarioModificacion) {
		this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
	}


	public Usuario getUsuarioByUsaurioAlta() {
		return this.usuarioByUsaurioAlta;
	}

	public void setUsuarioByUsaurioAlta(Usuario usuarioByUsaurioAlta) {
		this.usuarioByUsaurioAlta = usuarioByUsaurioAlta;
	}


	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}


	public String getNumeroExterior() {
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}


	public String getNumeroInterior() {
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}


	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}


	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}


	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}


	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}


	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}



}
