package mx.com.facturacion.factura;

public enum SeccionFacturaENUM {
	DOMICILIOS_EMPRESA,CLIENTES,CONCEPTOS,IMPUESTOS,SERIES_EMPRRESA,FOLIO_SERIE_EMPRESA,LUGAR_EXPEDICION,DOMICILIOS_CLIENTE,EMPRESA_LOGO,EMPRESA_PLAN;
}
