package mx.com.consolida.generico;

public enum CatMaestroEnum {
	
	VACACIONES( 1,"VAC","VACACIONES"),                     
	ZONA( 2,"ZONA","ZONA"),                                
	TIPO_NOMINA( 3,"TIP-NOM","TIPO_NOMINA"),               
	DIAS( 4,"DIAS","DIAS"),                                
	TIPO_IMMS( 5,"IMMS","TIPO_IMMS"),                      
	TIPO_PRESTACIONES( 6,"TIP-PRS","TIPO_PRESTACIONES"),   
	COSTEO_ASIMILABLE( 7,"COS-ASIM","COSTEO_ASIMILABLE"),  
	TIPO_COTIZACION( 8,"TIP-COTZ","TIPO_COTIZACION"),      
	ESTATUS( 9,"EST","Estatus"),
	TIPO_PERSONA( 10,"TIP_PERS","TIPO_PERSONA"),
	ENTIDAD_FEDERATIVA(11, "ENT_FED", "ENTIDAD_FEDERATIVA"),
	MUNICIPIOS(12, "MUNICIPIO", "MUNICIPIOS"),
	GIRO_COMERCIAL(13, "GIRO", "GIRO_COMERCIAL"),
	CATEGORIA(15, "CATEGORIA", "CATEGORIA"),
	BANCO_STP(18, "BANCO_STP", "BANCO STP"),
	CAT_FACULTADES(21, "FACULTADES", "FACULTADES"),
	TIPO_ESQUEMA(25, "TIP_ESQ", "TIPO_ESQUEMA"),
	TIPO_CUENTA_BANCARIA(26, "TIP_CUENTA", "TIPO_CUENTA_BANCARIA"),
	CANAL_VENTA(27, "TIP_CAN_VENT", "TIPO_CANAL_VENTA"),
	CAT_BANCOS(28, "CAT_BANCOS", "CAT_BANCOS"),
	METODO_PAGO(29, "METODO_PAGO", "METODO DE PAGO"),
	CAT_CONCEPTOSFDI(63, "CONCEPTO_FDI", "CONCEPTO_FDI"),
	CAT_TIPO_PAGO(61, "TIPO_PAGO", "TIPO PAGO"),
	CAT_SUBTIPOPAGO(62, "SUBTIPO_PAGO", "SUBTIPO PAGO"),
	CAT_TIPO_PRODUCTO_NOMINA(30, "TIPO_PROD_NOM", "TIPO PRODUCTO NOMINA"),
	CAT_USO_CFDI(31, "USO_CFDI", "USO CFDI"),
	CAT_TIPO_COMPROBANTE(32, "TIP_COMP", "TIPO DE COMPROBANTE"),
	CAT_REGIMEN_FISCAL(33, "REG_FISC", "REGIMEN FISCAL"),
	CAT_FORMA_PAGO(35, "FORM_PAGO", "FORMA DE PAGO"),
	VALOR_DEFAULT(37, "VALOR_DEFAULT", "Valor Default"),
	CAT_UNI_FACTURA(36, "CLAV_UNI", "CLAVE UNIDAD"),
	CAT_MONEDA(38, "MONEDA", "MONEDA"),
	PRODUCTO_SAT(40, "PRODUCTO_SAT", "CAT_PRODUCTO_SAT"),
	CAT_CLASE(41, "CLASE", "CAT_CLASE"),
	CAT_RIESGO(42, "RIESGO", "CAT_RIESGO"),
	PPP_SS(43, "PPP_SS", "PPP Y SUELDOS Y SALARIOS (IMSS)"),
	
	NACIONALIDAD(44,"NAC","NACIONALIDAD"),
	ESTADO_CIVIL (45,"EST-CIV","ESTADO CIVIL"),
	GENERO (46,"GEN","GENERO"),
	NIVEL_ESTUDIO (47,"NVL-EST","NIVEL DE ESTUDIO"),
	TIPO_JORNADA (48,"TIP-JOR","TIPO JORNADA"),
	TURNO (49,"TUR","TURNO"),
	TIPO_CONTRATO (50,"TIP-CONT","TIPO CONTRATO"),
	TIPO_INGRSOS (51,"TIP-ING","TIPO DE INGRESOS"),
	BENEFICIOS_ADICIONALES (52,"BEN-ADIC","BENEFICIOS ADICIONALES"),
	PORCENTAJE_COMISION(53,"POR_COM_REF","PORCENTAJE DE COMISION REFERIDO"),
	PROVEEDOR_TIMBRADO(54,"CAT_PROV_TIM","CAT PROVEEDOR TIMBRADO"),
	REPORTES(55,"CAT_REPOR","REPORTES"),
	TIPO_PERIODO(56,"TIPO_PERIODO","CAT_TIPO_PERIODO"),
	TIPO_DISPERSOR(58,"DISP","CAT_TIPO_DISPERSOR")
	;
			
	private int id;
	private String cve;
	private String desc;
	
	private CatMaestroEnum(int id, String cve, String desc) {
		this.id = id;
		this.cve = cve;
		this.desc = desc;
	}

	public final int getId() {
		return id;
	}

	public final String getCve() {
		return cve;
	}

	public final String getDesc() {
		return desc;
	}
	
}
