package mx.com.consolida.generico;

public enum CatTipoFormulaEnum {
	
	PRICING( 1,"PRINCING","COSTO DE OPERACIÓN"),
	COMISIONES_PPP( 2,"COMISIÓN PPP","PAGO A PROMOTORES PARA PPP"),
	COMISION_IMSS( 3,"COMISIÓN IMSS","PAGO A PROMOTOR POR IMSS"),
	HONORARIOS_PPP( 4,"HONORARIOS PPP","GANANCIAS POR PPP"),
	HONORARIOS_IMSS( 5,"HONORARIOS IMSS","GANANCIAS POR IMSS"),
	HONORARIOS_PPP_IVA( 6,"HONORARIO PPP IVA","IVA HONORARIO PPP"),
	HONORARIOS_PPP_FACTURA( 7,"HONORARIO PPP FACTURA","FORMULA FACTURA HONORARIO PPP"),
	HONORARIOS_PPP_FACTURA_SS( 8,"HONORARIO SUELDOS Y SALARIOS","HONORARIO SUELDOS Y SALARIOS"),
	HONORARIOS_PPP_FACTURA_MIXTO( 9,"HONORARIO MIXTO(PPP+IMSS)","HONORARIO MIXTO(PPP+IMSS)"),
	HONORARIOS_PPP_FACTURA_MAQUILA( 10,"HONORARIO MAQUILA","HONORARIO MAQUILA"),
	HONORARIOS_SS_IVA( 11,"IVA SUELDOS Y SALARIOS","IVA SUELDOS Y SALARIOS"),
	HONORARIOS_SS_FACTURA( 12,"FORMULA FACTURA SUELDOS Y SALARIOS","FORMULA FACTURA SUELDOS Y SALARIOS"),
	HONORARIOS_MIXTO_IVA( 13,"IVA MIXTO","IVA MIXTO"),
	HONORARIOS_MIXTO_FACTURA( 14,"FORMULA FACTURA MIXTO","FORMULA FACTURA MIXTO")
	;
	
	private int id;
	private String nombre;
	private String desc;
	
	private CatTipoFormulaEnum(int id, String nombre, String desc ) {
		this.id = id;
		this.nombre = nombre;
		this.desc = desc;
	}
	
	public int getId() {
		return id;
	}


	public String getNombre() {
		return nombre;
	}


	public String getDesc() {
		return desc;
	}

}
