package mx.com.consolida.generico;

public enum NominaEstatusEnum {

	BORRADOR(1, "BORR", "BORRADOR"),
	NOMINA_CARGADA(2, "NOM_CARG", "NOMINA CARGADA"),
	REQUIERE_FINANCIAMIENTO(3, "REQ_FINAN", "REQUIERE FINANCIAMIENTO"),
	AUTORIZADO_OPERACIONES(4, "AUT_OPERA", "AUTORIZADO OPERACIONES"),
	AUTORIZADO_FINANZAS(5, "AUT_FIN", "AUTORIZADO FINANZAS"),
	DEPOSITO_STP(6, "DEP_STP", "DEPOSITO STP"),
	FACTURA_GENERADA(7, "FACT_GEN", "FACTURA GENERADA"),
	ACEPTADA_CLIENTE(8, "ACEPT_CLIE", "ACEPTADA CLIENTE"),
	RECHAZADA_CLIENTE(9, "RECH_CLIE", "RECHAZADA CLIENTE"),
	EN_DISPERSION(10, "EN_DISPER", "EN DISPERSION"),
	DISPERSADA(11, "DISPER", "DISPERSADA"),
	EN_TIMBRADO(12, "EN_TIMBR", "EN TIMBRADO"),
	TIMBRADA(13, "TIMBRADA", "TIMBRADA"),
	RECHAZAR_FINANCIAMIENTO_OPER(14, "RECH_OPER", "RECHAZAR FINANCIAMIENTO OPERACIONES"),
	RECHAZAR_FINANCIAMIENTO_FINANZAS(15, "RECH_FINAN", "RECHAZAR FINANCIAMIENTO FINANZAS"),
	TIMBRADO_INCOMPLETO(16, "TIMBRADA_INC", "TIMBRADO INCOMPLETO"),
	FACTURA_CARGADA(17, "FACT_CARG", "FACTURA_CARGADA"),
	NOMINA_STP_GENERADA_EXITO(18, "NOM_STP_EXITO", "STP EXITOSO"),
	NOMINA_STP_GENERADA_ERRORES(19, "NOM_STP_ERROR", "STP CON ERRORES"),
	RECHAZAR_DISPERSION_STP(20, "RECH_DISP_FIN", "RECHAZAR DISPERSIÓN FINANZAS"),
	NOMINA_CANCELADA(21, "NOM_CANC", "NOMINA CANCELADA"),
	DISPERSADA_STP_CON_ERRORES(22, "DISPER_STP_ERROR", "DISPERSADA STP CON ERRORES"),
	CIERRE_NOMINA(23, "CIERRE_NOM", "CIERRE NOMINA"),
	COMPLEMENTO(24, "COMP_NOM", "COMPLEMENTO DE NOMINA"),
	CTA_CONCILIADA(25, "CTA_CON", "CUENTA CONCILIADA")
	;

	private int id;
	private String cve;
	private String desc;

	private NominaEstatusEnum(int id, String cve, String desc) {
		this.id = id;
		this.cve = cve;
		this.desc = desc;
	}

	public final int getId() {
		return id;
	}

	public final String getCve() {
		return cve;
	}

	public final String getDesc() {
		return desc;
	}

}
