package mx.com.consolida.entity.celula;
// Generated 6/05/2020 12:07:19 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.com.consolida.entity.crm.Cliente;
import mx.com.consolida.entity.prestadoraservicio.PrestadoraServicio;
import mx.com.consolida.entity.seguridad.Usuario;

/**
 * CelulaPrestadoraServicio generated by hbm2java
 */
@Entity
@Table(name = "celula_cliente")
@NamedQueries({ @NamedQuery(name = "CelulaCliente.findAll", query = "SELECT c FROM CelulaCliente c") })
public class CelulaCliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_celula_cliente")
	private Long idCelulaCliente;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_celula", nullable = false)
	private Celula celula;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	private Cliente cliente;
		
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_alta", nullable = false)
	private Usuario usuarioAlta;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_modificacion")
	private Usuario usuarioModificacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_alta", nullable = false, length = 19)
	private Date fechaAlta;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 19)
	private Date fechaModificacion;
	
	@Column(name = "ind_estatus", nullable = false)
	private Long indEstatus;

	public CelulaCliente() {
	}
	

	public CelulaCliente(Long idCelulaCliente) {
		this.idCelulaCliente = idCelulaCliente;
	}
	
	public CelulaCliente(Cliente cliente) {
		this.cliente=cliente;
	}
	
	public CelulaCliente(Long idCelulaCliente, Celula celula) {
		this.idCelulaCliente = idCelulaCliente;
		this.celula = celula;
	}
	

	public CelulaCliente(Celula celula, Cliente cliente, Usuario usuarioAlta,
			Date fechaAlta, Long indEstatus) {
		this.celula = celula;
		this.cliente = cliente;
		this.usuarioAlta = usuarioAlta;
		this.fechaAlta = fechaAlta;
		this.indEstatus = indEstatus;
	}

	public CelulaCliente(Celula celula, Cliente cliente, Usuario usuarioAlta,
			Date fechaAlta, Date fechaModificacion, Long indEstatus) {
		this.celula = celula;
		this.cliente = cliente;
		this.usuarioAlta = usuarioAlta;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.indEstatus = indEstatus;
	}


	public Long getIdCelulaCliente() {
		return idCelulaCliente;
	}

	public void setIdCelulaCliente(Long idCelulaCliente) {
		this.idCelulaCliente = idCelulaCliente;
	}

	public Celula getCelula() {
		return this.celula;
	}

	public void setCelula(Celula celula) {
		this.celula = celula;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Usuario getUsuarioAlta() {
		return usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	public Usuario getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	
	public Long getIndEstatus() {
		return this.indEstatus;
	}

	public void setIndEstatus(Long indEstatus) {
		this.indEstatus = indEstatus;
	}

}
