
package com.lgec.enlacefi.spei.integration.h2h;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpeiActualizaServicesImpl", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", wsdlLocation = "https://demo.stpmex.com:7024/spei/webservices/SpeiActualizaServices?wsdl")
public class SpeiActualizaServicesImpl
    extends Service
{

    private final static URL SPEIACTUALIZASERVICESIMPL_WSDL_LOCATION;
    private final static WebServiceException SPEIACTUALIZASERVICESIMPL_EXCEPTION;
    private final static QName SPEIACTUALIZASERVICESIMPL_QNAME = new QName("http://h2h.integration.spei.enlacefi.lgec.com/", "SpeiActualizaServicesImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://demo.stpmex.com:7024/spei/webservices/SpeiActualizaServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPEIACTUALIZASERVICESIMPL_WSDL_LOCATION = url;
        SPEIACTUALIZASERVICESIMPL_EXCEPTION = e;
    }

    public SpeiActualizaServicesImpl() {
        super(__getWsdlLocation(), SPEIACTUALIZASERVICESIMPL_QNAME);
    }

    public SpeiActualizaServicesImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPEIACTUALIZASERVICESIMPL_QNAME, features);
    }

    public SpeiActualizaServicesImpl(URL wsdlLocation) {
        super(wsdlLocation, SPEIACTUALIZASERVICESIMPL_QNAME);
    }

    public SpeiActualizaServicesImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPEIACTUALIZASERVICESIMPL_QNAME, features);
    }

    public SpeiActualizaServicesImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpeiActualizaServicesImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SpeiActualizaServices
     */
    @WebEndpoint(name = "SpeiActualizaServicesImplPort")
    public SpeiActualizaServices getSpeiActualizaServicesImplPort() {
        return super.getPort(new QName("http://h2h.integration.spei.enlacefi.lgec.com/", "SpeiActualizaServicesImplPort"), SpeiActualizaServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpeiActualizaServices
     */
    @WebEndpoint(name = "SpeiActualizaServicesImplPort")
    public SpeiActualizaServices getSpeiActualizaServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://h2h.integration.spei.enlacefi.lgec.com/", "SpeiActualizaServicesImplPort"), SpeiActualizaServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPEIACTUALIZASERVICESIMPL_EXCEPTION!= null) {
            throw SPEIACTUALIZASERVICESIMPL_EXCEPTION;
        }
        return SPEIACTUALIZASERVICESIMPL_WSDL_LOCATION;
    }

}
