
package com.lgec.enlacefi.spei.integration.h2h;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpeiActualizaServices", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpeiActualizaServices {


    /**
     * 
     * @param ordenesTraspasos
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.ResponseOrdenTraspaso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registraOrdenesTraspasos", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenesTraspasos")
    @ResponseWrapper(localName = "registraOrdenesTraspasosResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenesTraspasosResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraOrdenesTraspasosRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraOrdenesTraspasosResponse")
    public ResponseOrdenTraspaso registraOrdenesTraspasos(
        @WebParam(name = "ordenesTraspasos", targetNamespace = "")
        OrdenesTraspasos ordenesTraspasos,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param ordenPago
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registraOrden", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrden")
    @ResponseWrapper(localName = "registraOrdenResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraOrdenRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraOrdenResponse")
    public SpeiServiceResponse registraOrden(
        @WebParam(name = "ordenPago", targetNamespace = "")
        OrdenPagoWS ordenPago,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param claveRastreo
     * @param montoRetorno
     * @param beneficiarioRetorno
     * @param claveInstitucionOrdenante
     * @param usuario
     * @param medioEntrega
     * @param claveRastreoRetorno
     * @param fechaOperacion
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retornaOrden", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RetornaOrden")
    @ResponseWrapper(localName = "retornaOrdenResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RetornaOrdenResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/retornaOrdenRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/retornaOrdenResponse")
    public SpeiServiceResponse retornaOrden(
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        Integer fechaOperacion,
        @WebParam(name = "claveInstitucionOrdenante", targetNamespace = "")
        Integer claveInstitucionOrdenante,
        @WebParam(name = "claveRastreo", targetNamespace = "")
        String claveRastreo,
        @WebParam(name = "montoRetorno", targetNamespace = "")
        BigDecimal montoRetorno,
        @WebParam(name = "beneficiarioRetorno", targetNamespace = "")
        Integer beneficiarioRetorno,
        @WebParam(name = "claveRastreoRetorno", targetNamespace = "")
        String claveRastreoRetorno,
        @WebParam(name = "medioEntrega", targetNamespace = "")
        Integer medioEntrega,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param nuevoRastreo
     * @param causaDevolucion
     * @param razonRechazo
     * @param usuario
     * @param medioEntrega
     * @param idOrden
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "devuelveOrdenRazonRechazo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenRazonRechazo")
    @ResponseWrapper(localName = "devuelveOrdenRazonRechazoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenRazonRechazoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/devuelveOrdenRazonRechazoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/devuelveOrdenRazonRechazoResponse")
    public SpeiServiceResponse devuelveOrdenRazonRechazo(
        @WebParam(name = "idOrden", targetNamespace = "")
        Integer idOrden,
        @WebParam(name = "causaDevolucion", targetNamespace = "")
        Integer causaDevolucion,
        @WebParam(name = "nuevoRastreo", targetNamespace = "")
        String nuevoRastreo,
        @WebParam(name = "medioEntrega", targetNamespace = "")
        Integer medioEntrega,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "razonRechazo", targetNamespace = "")
        String razonRechazo,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param id
     * @param detalleError
     * @param fechOper
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "regDetalleErrEnvExtemp", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegDetalleErrEnvExtemp")
    @ResponseWrapper(localName = "regDetalleErrEnvExtempResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegDetalleErrEnvExtempResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/regDetalleErrEnvExtempRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/regDetalleErrEnvExtempResponse")
    public void regDetalleErrEnvExtemp(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "detalleError", targetNamespace = "")
        String detalleError,
        @WebParam(name = "fechOper", targetNamespace = "")
        Integer fechOper,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param id
     * @param detalleError
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "registraDetalleErrorEnvio", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraDetalleErrorEnvio")
    @ResponseWrapper(localName = "registraDetalleErrorEnvioResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraDetalleErrorEnvioResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraDetalleErrorEnvioRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraDetalleErrorEnvioResponse")
    public void registraDetalleErrorEnvio(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "detalleError", targetNamespace = "")
        String detalleError,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param id
     * @param detalleError
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "registraDetalleErrorRecepcion", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraDetalleErrorRecepcion")
    @ResponseWrapper(localName = "registraDetalleErrorRecepcionResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraDetalleErrorRecepcionResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraDetalleErrorRecepcionRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraDetalleErrorRecepcionResponse")
    public void registraDetalleErrorRecepcion(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "detalleError", targetNamespace = "")
        String detalleError,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param instContraparte
     * @param rastreo
     * @param fechaOperacion
     * @param token
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tiempoEntregaAbonoRastreo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaAbonoRastreo")
    @ResponseWrapper(localName = "tiempoEntregaAbonoRastreoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaAbonoRastreoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/tiempoEntregaAbonoRastreoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/tiempoEntregaAbonoRastreoResponse")
    public Long tiempoEntregaAbonoRastreo(
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        Integer fechaOperacion,
        @WebParam(name = "rastreo", targetNamespace = "")
        String rastreo,
        @WebParam(name = "instContraparte", targetNamespace = "")
        Integer instContraparte,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param delay
     * @param idEF
     * @param rfc
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmaAbonoDelay", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoDelay")
    @ResponseWrapper(localName = "confirmaAbonoDelayResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoDelayResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaAbonoDelayRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaAbonoDelayResponse")
    public SpeiServiceResponse confirmaAbonoDelay(
        @WebParam(name = "idEF", targetNamespace = "")
        Integer idEF,
        @WebParam(name = "rfc", targetNamespace = "")
        String rfc,
        @WebParam(name = "delay", targetNamespace = "")
        Long delay,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param idEF
     * @param rfc
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmaAbonoId", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoId")
    @ResponseWrapper(localName = "confirmaAbonoIdResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoIdResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaAbonoIdRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaAbonoIdResponse")
    public SpeiServiceResponse confirmaAbonoId(
        @WebParam(name = "idEF", targetNamespace = "")
        Integer idEF,
        @WebParam(name = "rfc", targetNamespace = "")
        String rfc,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param claveRastreo
     * @param institucionContraparte
     * @param rfc
     * @param fechaOperacion
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmaAbono", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbono")
    @ResponseWrapper(localName = "confirmaAbonoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaAbonoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaAbonoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaAbonoResponse")
    public SpeiServiceResponse confirmaAbono(
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        Integer fechaOperacion,
        @WebParam(name = "institucionContraparte", targetNamespace = "")
        Integer institucionContraparte,
        @WebParam(name = "claveRastreo", targetNamespace = "")
        String claveRastreo,
        @WebParam(name = "rfc", targetNamespace = "")
        String rfc,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reenviaErroresH2H", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ReenviaErroresH2H")
    @ResponseWrapper(localName = "reenviaErroresH2HResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ReenviaErroresH2HResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/reenviaErroresH2HRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/reenviaErroresH2HResponse")
    public String reenviaErroresH2H(
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param ordenesPago
     * @param token
     * @return
     *     returns java.util.List<com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registraOrdenes", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenes")
    @ResponseWrapper(localName = "registraOrdenesResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraOrdenesResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraOrdenesRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraOrdenesResponse")
    public List<SpeiServiceResponse> registraOrdenes(
        @WebParam(name = "ordenesPago", targetNamespace = "")
        List<OrdenPagoWS> ordenesPago,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param nuevoRastreo
     * @param causaDevolucion
     * @param usuario
     * @param medioEntrega
     * @param idOrden
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "devuelveOrden", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrden")
    @ResponseWrapper(localName = "devuelveOrdenResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/devuelveOrdenRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/devuelveOrdenResponse")
    public SpeiServiceResponse devuelveOrden(
        @WebParam(name = "idOrden", targetNamespace = "")
        Integer idOrden,
        @WebParam(name = "causaDevolucion", targetNamespace = "")
        Integer causaDevolucion,
        @WebParam(name = "nuevoRastreo", targetNamespace = "")
        String nuevoRastreo,
        @WebParam(name = "medioEntrega", targetNamespace = "")
        Integer medioEntrega,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param claveRastreo
     * @param nuevoRastreo
     * @param causaDevolucion
     * @param usuario
     * @param claveInstitucion
     * @param medioEntrega
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "devuelveOrdenClaveRastreo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenClaveRastreo")
    @ResponseWrapper(localName = "devuelveOrdenClaveRastreoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenClaveRastreoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/devuelveOrdenClaveRastreoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/devuelveOrdenClaveRastreoResponse")
    public SpeiServiceResponse devuelveOrdenClaveRastreo(
        @WebParam(name = "claveInstitucion", targetNamespace = "")
        Integer claveInstitucion,
        @WebParam(name = "claveRastreo", targetNamespace = "")
        String claveRastreo,
        @WebParam(name = "causaDevolucion", targetNamespace = "")
        Integer causaDevolucion,
        @WebParam(name = "nuevoRastreo", targetNamespace = "")
        String nuevoRastreo,
        @WebParam(name = "medioEntrega", targetNamespace = "")
        Integer medioEntrega,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param claveRastreo
     * @param causaDevolucion
     * @param usuario
     * @param claveInstitucion
     * @param medioEntrega
     * @param montoInteres
     * @param fechaOperacion
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "devuelveOrdenExtemporanea", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenExtemporanea")
    @ResponseWrapper(localName = "devuelveOrdenExtemporaneaResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DevuelveOrdenExtemporaneaResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/devuelveOrdenExtemporaneaRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/devuelveOrdenExtemporaneaResponse")
    public SpeiServiceResponse devuelveOrdenExtemporanea(
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        Integer fechaOperacion,
        @WebParam(name = "claveInstitucion", targetNamespace = "")
        Integer claveInstitucion,
        @WebParam(name = "claveRastreo", targetNamespace = "")
        String claveRastreo,
        @WebParam(name = "causaDevolucion", targetNamespace = "")
        Integer causaDevolucion,
        @WebParam(name = "medioEntrega", targetNamespace = "")
        Integer medioEntrega,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "montoInteres", targetNamespace = "")
        BigDecimal montoInteres,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param nuevoEstado
     * @param folio
     * @param razonCancelacion
     * @param idOrden
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmaCargo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaCargo")
    @ResponseWrapper(localName = "confirmaCargoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaCargoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaCargoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaCargoResponse")
    public SpeiServiceResponse confirmaCargo(
        @WebParam(name = "idOrden", targetNamespace = "")
        Integer idOrden,
        @WebParam(name = "razonCancelacion", targetNamespace = "")
        String razonCancelacion,
        @WebParam(name = "nuevoEstado", targetNamespace = "")
        String nuevoEstado,
        @WebParam(name = "folio", targetNamespace = "")
        String folio,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param claveRastreo
     * @param nuevoEstado
     * @param folio
     * @param institucionOperante
     * @param razonCancelacion
     * @param fechaOperacion
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmaCargoRastreo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaCargoRastreo")
    @ResponseWrapper(localName = "confirmaCargoRastreoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConfirmaCargoRastreoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaCargoRastreoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/confirmaCargoRastreoResponse")
    public SpeiServiceResponse confirmaCargoRastreo(
        @WebParam(name = "institucionOperante", targetNamespace = "")
        Integer institucionOperante,
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        Integer fechaOperacion,
        @WebParam(name = "claveRastreo", targetNamespace = "")
        String claveRastreo,
        @WebParam(name = "razonCancelacion", targetNamespace = "")
        String razonCancelacion,
        @WebParam(name = "nuevoEstado", targetNamespace = "")
        String nuevoEstado,
        @WebParam(name = "folio", targetNamespace = "")
        String folio,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param idOrden
     * @param token
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tiempoEntregaAbono", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaAbono")
    @ResponseWrapper(localName = "tiempoEntregaAbonoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaAbonoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/tiempoEntregaAbonoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/tiempoEntregaAbonoResponse")
    public Long tiempoEntregaAbono(
        @WebParam(name = "idOrden", targetNamespace = "")
        Integer idOrden,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param idOrden
     * @param token
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tiempoEntregaCargo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaCargo")
    @ResponseWrapper(localName = "tiempoEntregaCargoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaCargoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/tiempoEntregaCargoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/tiempoEntregaCargoResponse")
    public Long tiempoEntregaCargo(
        @WebParam(name = "idOrden", targetNamespace = "")
        Integer idOrden,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param instOperante
     * @param rastreo
     * @param fechaOperacion
     * @param token
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tiempoEntregaCargoRastreo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaCargoRastreo")
    @ResponseWrapper(localName = "tiempoEntregaCargoRastreoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TiempoEntregaCargoRastreoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/tiempoEntregaCargoRastreoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/tiempoEntregaCargoRastreoResponse")
    public Long tiempoEntregaCargoRastreo(
        @WebParam(name = "fechaOperacion", targetNamespace = "")
        Integer fechaOperacion,
        @WebParam(name = "rastreo", targetNamespace = "")
        String rastreo,
        @WebParam(name = "instOperante", targetNamespace = "")
        Integer instOperante,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param monto
     * @param cuentaDestino
     * @param cuentaOrigen
     * @param usuario
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "traspasoEntreCuentas", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TraspasoEntreCuentas")
    @ResponseWrapper(localName = "traspasoEntreCuentasResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.TraspasoEntreCuentasResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/traspasoEntreCuentasRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/traspasoEntreCuentasResponse")
    public SpeiServiceResponse traspasoEntreCuentas(
        @WebParam(name = "cuentaOrigen", targetNamespace = "")
        String cuentaOrigen,
        @WebParam(name = "cuentaDestino", targetNamespace = "")
        String cuentaDestino,
        @WebParam(name = "monto", targetNamespace = "")
        String monto,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param instOperante
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "conecta", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.Conecta")
    @ResponseWrapper(localName = "conectaResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ConectaResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/conectaRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/conectaResponse")
    public void conecta(
        @WebParam(name = "instOperante", targetNamespace = "")
        Integer instOperante,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param instOperante
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "desconecta", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.Desconecta")
    @ResponseWrapper(localName = "desconectaResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.DesconectaResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/desconectaRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/desconectaResponse")
    public void desconecta(
        @WebParam(name = "instOperante", targetNamespace = "")
        Integer instOperante,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param numeroCelular
     * @param empresa
     * @param cuentaCLABE
     * @param firma
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "asociaNumeroCelular", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.AsociaNumeroCelular")
    @ResponseWrapper(localName = "asociaNumeroCelularResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.AsociaNumeroCelularResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/asociaNumeroCelularRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/asociaNumeroCelularResponse")
    public SpeiServiceResponse asociaNumeroCelular(
        @WebParam(name = "empresa", targetNamespace = "")
        String empresa,
        @WebParam(name = "numeroCelular", targetNamespace = "")
        String numeroCelular,
        @WebParam(name = "cuentaCLABE", targetNamespace = "")
        String cuentaCLABE,
        @WebParam(name = "firma", targetNamespace = "")
        String firma,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param estado
     * @param instOperante
     * @param nombreBeneficiario
     * @param cuenta
     * @param empresa
     * @param nombre
     * @param rfc
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.AltaCuentaTercerosReturn
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "altaCuentaTerceros", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.AltaCuentaTerceros")
    @ResponseWrapper(localName = "altaCuentaTercerosResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.AltaCuentaTercerosResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/altaCuentaTercerosRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/altaCuentaTercerosResponse")
    public AltaCuentaTercerosReturn altaCuentaTerceros(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "nombreBeneficiario", targetNamespace = "")
        String nombreBeneficiario,
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta,
        @WebParam(name = "rfc", targetNamespace = "")
        String rfc,
        @WebParam(name = "empresa", targetNamespace = "")
        String empresa,
        @WebParam(name = "estado", targetNamespace = "")
        String estado,
        @WebParam(name = "instOperante", targetNamespace = "")
        Integer instOperante,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param traspaso
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.SpeiServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registraTraspaso", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraTraspaso")
    @ResponseWrapper(localName = "registraTraspasoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.RegistraTraspasoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraTraspasoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/registraTraspasoResponse")
    public SpeiServiceResponse registraTraspaso(
        @WebParam(name = "traspaso", targetNamespace = "")
        TraspasoWS traspaso,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param cadenaOriginal
     * @param serieCertificado
     * @param firma
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.RespuestaCodi
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "aRegistraCobro", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ARegistraCobro")
    @ResponseWrapper(localName = "aRegistraCobroResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ARegistraCobroResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/aRegistraCobroRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/aRegistraCobroResponse")
    public RespuestaCodi aRegistraCobro(
        @WebParam(name = "cadenaOriginal", targetNamespace = "")
        String cadenaOriginal,
        @WebParam(name = "serieCertificado", targetNamespace = "")
        String serieCertificado,
        @WebParam(name = "firma", targetNamespace = "")
        String firma,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param cadenaOriginal
     * @param serieCertificado
     * @param claveInst
     * @param firma
     * @param tsSolicitudOriginal
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.RespuestaCodi
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "aRegistraEstadoCobro", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ARegistraEstadoCobro")
    @ResponseWrapper(localName = "aRegistraEstadoCobroResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.ARegistraEstadoCobroResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/aRegistraEstadoCobroRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/aRegistraEstadoCobroResponse")
    public RespuestaCodi aRegistraEstadoCobro(
        @WebParam(name = "cadenaOriginal", targetNamespace = "")
        String cadenaOriginal,
        @WebParam(name = "serieCertificado", targetNamespace = "")
        String serieCertificado,
        @WebParam(name = "claveInst", targetNamespace = "")
        String claveInst,
        @WebParam(name = "tsSolicitudOriginal", targetNamespace = "")
        String tsSolicitudOriginal,
        @WebParam(name = "firma", targetNamespace = "")
        String firma,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param cadenaOriginal
     * @param idc
     * @param serieCertificado
     * @param claveInst
     * @param firma
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.RespuestaBajaDispositivos
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "abajaDispositivo", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.AbajaDispositivo")
    @ResponseWrapper(localName = "abajaDispositivoResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.AbajaDispositivoResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/abajaDispositivoRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/abajaDispositivoResponse")
    public RespuestaBajaDispositivos abajaDispositivo(
        @WebParam(name = "cadenaOriginal", targetNamespace = "")
        String cadenaOriginal,
        @WebParam(name = "serieCertificado", targetNamespace = "")
        String serieCertificado,
        @WebParam(name = "claveInst", targetNamespace = "")
        String claveInst,
        @WebParam(name = "idc", targetNamespace = "")
        String idc,
        @WebParam(name = "firma", targetNamespace = "")
        String firma,
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param empresa
     * @param token
     * @return
     *     returns com.lgec.enlacefi.spei.integration.h2h.DesactivaEnvioH2HResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adesactivaEnvioH2H", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.AdesactivaEnvioH2H")
    @ResponseWrapper(localName = "adesactivaEnvioH2HResponse", targetNamespace = "http://h2h.integration.spei.enlacefi.lgec.com/", className = "com.lgec.enlacefi.spei.integration.h2h.AdesactivaEnvioH2HResponse")
    @Action(input = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/adesactivaEnvioH2HRequest", output = "http://h2h.integration.spei.enlacefi.lgec.com/SpeiActualizaServices/adesactivaEnvioH2HResponse")
    public DesactivaEnvioH2HResponse adesactivaEnvioH2H(
        @WebParam(name = "empresa", targetNamespace = "")
        String empresa,
        @WebParam(name = "token", targetNamespace = "")
        String token);

}
